<?php

use Illuminate\Database\Seeder;

class IndicatorCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('indicator_category')->insert(
            [
                [
                    // 'id' => 1,
                    'name' => 'KESEHATAN IBU DAN ANAK',
                    'label' => 'PENGAMATAN PENYAKIT MENULAR',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 2,
                    'name' => 'PENGAMATAN PENYAKIT MENULAR',
                    'label' => 'PENGAMATAN PENYAKIT MENULAR',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 3,
                    'name' => 'KUNJUNGAN PUSKESMAS',
                    'label' => 'KUNJUNGAN PUSKESMAS',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 4,
                    'name' => 'RAWAT TINGGAL',
                    'label' => 'RAWAT TINGGAL',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 5,
                    'name' => 'KEGIATAN PERAWATAN KESEHATAN MASYARAKAT',
                    'label' => 'KEGIATAN PERAWATAN KESEHATAN MASYARAKAT',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 6,
                    'name' => 'FREKUENSI KEGIATAN PUSKESMAS DILUAR GEDUNG',
                    'label' => 'FREKUENSI KEGIATAN PUSKESMAS DILUAR GEDUNG',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 7,
                    'name' => 'PENDUDUK YANG MENGGUNAKAN SARANAN KESEHATAN SWASTA',
                    'label' => 'PENDUDUK YANG MENGGUNAKAN SARANAN KESEHATAN SWASTA',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 8,
                    'name' => 'PELAYANAN MEDIK DASAR KESEHATAN GIGI',
                    'label' => 'PELAYANAN MEDIK DASAR KESEHATAN GIGI',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 9,
                    'name' => 'KEGIATAN PELAYANAN JPKM',
                    'label' => 'KEGIATAN PELAYANAN JPKM',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 10,
                    'name' => 'KEGIATAN SEKOLAH',
                    'label' => 'KEGIATAN SEKOLAH',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 11,
                    'name' => 'KESEHATAN OLAH RAGA',
                    'label' => 'KESEHATAN OLAH RAGA',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 12,
                    'name' => 'KESEHATAN OLAH RAGA',
                    'label' => 'KESEHATAN OLAH RAGA',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 13,
                    'name' => 'KEGIATAN PENYULUHAN KESEHATAN MASYARAKAT',
                    'label' => 'KEGIATAN PENYULUHAN KESEHATAN MASYARAKAT',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 14,
                    'name' => 'KEGIATAN UKBM',
                    'label' => 'KEGIATAN UKBM',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 15,
                    'name' => 'KESEHATAN LINGKUNGAN',
                    'label' => 'KESEHATAN LINGKUNGAN',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 16,
                    'name' => 'LABORATORIUM',
                    'label' => 'LABORATORIUM',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 17,
                    'name' => 'JAMINAN MUTU / QUALITY ASSURANCE',
                    'label' => 'JAMINAN MUTU / QUALITY ASSURANCE',
                    'parent_category_id' => null,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 18,
                    'name' => 'Gizi',
                    'label' => 'Gizi',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 19,
                    'name' => 'Upaya Penanggulangan Anemia Gizi Besi (Fe)',
                    'label' => 'Upaya Penanggulangan Anemia Gizi Besi (Fe)',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 20,
                    'name' => 'Upaya Pemantauan Pertumbuhan Balita',
                    'label' => 'Upaya Pemantauan Pertumbuhan Balita',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 21,
                    'name' => 'Upaya Penanggulangan Gangguan Akibat Kekurangan Yodium (G',
                    'label' => 'Upaya Penanggulangan Gangguan Akibat Kekurangan Yodium (G',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 22,
                    'name' => 'Upaya Penanggulangan Kekurangan Energi Kronis (KEK)',
                    'label' => 'Upaya Penanggulangan Kekurangan Energi Kronis (KEK)',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 23,
                    'name' => 'Pelayanan Ibu Hamil',
                    'label' => 'Pelayanan Ibu Hamil',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 24,
                    'name' => 'Pelayanan Persalinan ',
                    'label' => 'Pelayanan Persalinan ',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 25,
                    'name' => 'Pelayanan Ibu Menyusui',
                    'label' => 'Pelayanan Ibu Menyusui',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 26,
                    'name' => 'Pelayanan Bayi',
                    'label' => 'Pelayanan Bayi',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 27,
                    'name' => 'Pelayanan Anak Balita',
                    'label' => 'Pelayanan Anak Balita',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 28,
                    'name' => 'IMUNISASI',
                    'label' => 'IMUNISASI',
                    'parent_category_id' => 1,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 29,
                    'name' => 'Acute Flaccid Paralysis (AFP) ',
                    'label' => 'Acute Flaccid Paralysis (AFP) ',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 30,
                    'name' => 'Tetanus Neonatorum ',
                    'label' => 'Tetanus Neonatorum ',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 31,
                    'name' => 'Malaria',
                    'label' => 'Malaria',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 32,
                    'name' => 'D B D (Demam Berdarah Dengue) ',
                    'label' => 'D B D (Demam Berdarah Dengue) ',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 33,
                    'name' => 'R a b i e s ',
                    'label' => 'R a b i e s ',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 34,
                    'name' => 'Filaria',
                    'label' => 'Filaria',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 35,
                    'name' => 'PENYAKIT ZOONOSIS LAIN (Antraks)',
                    'label' => 'PENYAKIT ZOONOSIS LAIN (Antraks)',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 36,
                    'name' => 'Frambusia',
                    'label' => 'Frambusia',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 37,
                    'name' => 'Diare',
                    'label' => 'Diare',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 38,
                    'name' => 'ISPA',
                    'label' => 'ISPA',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 39,
                    'name' => 'TB Paru',
                    'label' => 'TB Paru',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 40,
                    'name' => 'Kusta',
                    'label' => 'Kusta',
                    'parent_category_id' => 2,
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
            ]
        );
    }
}
