<?php

use Illuminate\Database\Seeder;

class LB3ProductionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $parent = [
            [ // main parent
                'id' => 3500,
                'name' => 'kesehatan_ibu_dan_anak',
                'label' => 'Kesehatan Ibu Dan Anak',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // sub-parent
                'id' => 3501,
                'name' => 'kesehatan_ibu_dan_anak_gizi',
                'label' => 'Gizi',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3502,
                'name' => 'upaya_penanggulangan_anemia_gizi_besi_fe',
                'label' => 'Upaya Penanggulangan Anemia Gizi Besi (Fe)',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3503,
                'name' => 'upaya_pemantauan_pertumbuhan_balita',
                'label' => 'Upaya Pemantauan Pertumbuhan Balita',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3504,
                'name' => 'upaya_penanggulangan_gangguan_akibat_kekurangan_yodium_gaky',
                'label' => 'Upaya Penanggulangan Gangguan Akibat Kekurangan Yodium (GAKY)',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3505,
                'name' => 'upaya_penaggulangan_kekurangan_energi_kronis_kek',
                'label' => 'Upaya Penanggulangan Kekurangan Energi Kronis (KEK)',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3506,
                'name' => 'pelayanan_ibu_hamil',
                'label' => 'Pelayanan Ibu Hamil',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3507,
                'name' => 'pelayanan_persalinan',
                'label' => 'Pelayanan Persalinan',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3508,
                'name' => 'pelayanan_ibu_menyusui',
                'label' => ' Pelayanan Ibu Menyusui ',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3509,
                'name' => 'pelayanan_bayi',
                'label' => 'Pelayanan Bayi',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3510,
                'name' => 'pelayanan_anak_balita',
                'label' => 'Pelayanan Anak Balita',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3511,
                'name' => 'imunisasi',
                'label' => 'IMUNISASI',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3512,
                'name' => 'pengamatan_penyakit_menular',
                'label' => 'PENGAMATAN PENYAKIT MENULAR',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3513,
                'name' => 'acute_flaccid_paralysis_afp',
                'label' => 'Acute Flaccid Paralysis (AFP)',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3514,
                'name' => 'tetanus_neonatorum',
                'label' => 'Tetanus Neonatorum',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3515,
                'name' => 'malaria',
                'label' => 'Malaria',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3516,
                'name' => 'dbd_demam_berdarah_dengue',
                'label' => 'DBD (Demam Berdarah Dengue)',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3517,
                'name' => 'rabies',
                'label' => 'Rabies',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3518,
                'name' => 'filaria',
                'label' => 'Filaria',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3519,
                'name' => 'penyakit_zoonosis_lain_antraks',
                'label' => 'PENYAKIT ZOONOSIS LAIN (Antraks)',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3520,
                'name' => 'frambusia',
                'label' => 'Frambusia',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3521,
                'name' => 'diare',
                'label' => 'Diare',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3522,
                'name' => 'ispa',
                'label' => 'ISPA',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3523,
                'name' => 'tb_paru',
                'label' => 'TB Paru',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3524,
                'name' => 'kusta',
                'label' => 'Kusta',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3501 child
                'id' => 3525,
                'name' => 'upaya_penanggulangan_kekurangan_vitamin_a',
                'label' => 'Upaya Penanggulangan Kekurangan Vitamin A',
                'is_parent' => false,
                'indicator_parent_id' => 3501,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3501 child
                'id' => 3526,
                'name' => 'jumlah_anak_balita_1_5_th_dapat_kapsul_vit_a_dosis_tinggi_200000_IU_bulan_ini',
                'label' => 'Jumlah anak balita (1-5 th) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3501,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3501 child
                'id' => 3527,
                'name' => 'jumlah_ibu_nifas_sd_40_hr_dapat_kapsul_vit_a_dosis_tinggi_200000_iu_bulan_ini',
                'label' => 'Jumlah Ibu nifas (s/d 40 hr) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3501,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3501 child
                'id' => 3528,
                'name' => 'jumlah_bayi_6_11_th_dapat_kapsul_vit_a_dosis_tinggi_200000_iu_bulan_ini',
                'label' => 'Jumlah bayi (6-11 th) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3501,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3529,
                'name' => 'jumlah_ibu_hamil_dapat_tablet_tambah_darah_fe_30_tablet_fe1_bulan_ini',
                'label' => 'Jumlah Ibu hamil dapat tablet tambah darah (Fe) 30 tablet (Fe1) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3530,
                'name' => 'jumlah_ibu_hamil_dapat_tablet_tambah_darah_fe_90_tablet_fe2_bulan_ini',
                'label' => 'Jumlah Ibu hamil dapat tablet tambah darah (Fe) 90 tablet (Fe2) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3531,
                'name' => 'jumlah_balita_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah Balita diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3532,
                'name' => 'jumlah_balita_yang_diperiksa_dengan_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah Balita yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3533,
                'name' => 'jumlah_wus_15_45_th_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah WUS (15 - 45 th) diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3534,
                'name' => 'jumlah_wus_15_45_th_yang_diperiksa_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah WUS (15 - 45 th) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3535,
                'name' => 'jumlah_remaja_putri_14_18_th_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah Remaja Putri (14 - 18 th) diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3536,
                'name' => 'jumlah_remaja_putri_14_18_th_yang_diperiksa_dengan_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah Remaja Putri (14 - 18 th) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3537,
                'name' => 'jumlah_tenaga_kerja_wanita_nakerwan_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah Tenaga Kerja Wanita (nakerwan) diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3538,
                'name' => 'jumlah_tenaga_kerja_wanita_nakerwan_yang_diperiksa_dengan_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah Tenaga Kerja Wanita (nakerwan) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3539,
                'name' => 'jumlah_ibu_hamil_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah Ibu hamil diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3540,
                'name' => 'jumlah_ibu_hamil_yang_diperiksa_dengan_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah Ibu hamil yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3541,
                'name' => 'jumlah_balita_yang_ada_bulan_ini',
                'label' => 'Jumlah Balita yang ada bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3542,
                'name' => 'jumlah_balita_yang_mempunyai_kms_bulan_ini',
                'label' => 'Jumlah Balita yang mempunyai KMS bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3543,
                'name' => 'jumlah_balita_yang_naik_berat_badannya_bulan_ini',
                'label' => 'Jumlah Balita yang Naik berat badannya bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3544,
                'name' => 'jumlah_balita_yang_tidak_naik_tetap_berat_badannya_bulan_ini',
                'label' => 'Jumlah Balita yang Tidak naik/tetap berat badannya bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3545,
                'name' => 'jumlah_balita_yang_ditimbang_bulan_ini_tetapi_tidak_ditimbang_bulan_lalu',
                'label' => 'Jumlah Balita yang ditimbang bulan ini tetapi tidak ditimbang bulan lalu',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3546,
                'name' => 'jumlah_balita_yang_baru_ditimbang_bulan_ini',
                'label' => 'Jumlah Balita yang Baru ditimbang bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3547,
                'name' => 'jumlah_balita_yang_dapat_ditimbang_bulan_ini',
                'label' => 'Jumlah Balita yang dapat ditimbang bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3548,
                'name' => 'jumlah_balita_yang_tidak_dapat_ditimbang_bulan_ini',
                'label' => 'Jumlah Balita yang tidak dapat ditimbang bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3549,
                'name' => 'jumlah_balita_dengan_berat_badan_di_bawah_garis_merah_bgm_bulan_ini',
                'label' => 'Jumlah Balita dengan Berat badan di Bawah Garis Merah (BGM) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3550,
                'name' => 'jumlah_balita_gizi_buruk_bulan_ini',
                'label' => 'Jumlah Balita gizi buruk bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3504 child
                'id' => 3551,
                'name' => 'jumlah_penderita_gaky_laki_laki_bulan_ini',
                'label' => 'Jumlah penderita GAKY laki-laki bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3504,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3504 child
                'id' => 3552,
                'name' => 'jumlah_penderita_gaky_perempuan_bulan_ini',
                'label' => 'Jumlah penderita GAKY perempuan bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3504,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3504 child
                'id' => 3553,
                'name' => 'jumlah_ibu_hamil_mendapat_kapsul_yodium',
                'label' => 'Jumlah ibu hamil mendapat kapsul yodium',
                'is_parent' => false,
                'indicator_parent_id' => 3504,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3504 child
                'id' => 3554,
                'name' => 'jumlah_penduduk_lainnya_mendapat_kapsul_yodium',
                'label' => 'Jumlah penduduk lainnya mendapat kapsul yodium',
                'is_parent' => false,
                'indicator_parent_id' => 3504,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3505 child
                'id' => 3555,
                'name' => 'jumlah_ibu_hamil_baru_diukur_lila_lingkar_lengan_atas_bulan_ini',
                'label' => 'Jumlah Ibu hamil baru, diukur LILA (Lingkar Lengan Atas) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3505,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3505 child
                'id' => 3556,
                'name' => 'jumlah_ibu_hamil_baru_dengan_lila_23_5_cm_bulan_ini',
                'label' => 'Jumlah Ibu hamil baru, dengan LILA < 23,5 cm bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3505,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3505 child
                'id' => 3556,
                'name' => 'jumlah_wus_baru_yang_diukur_lila_lingkar_lengan_atas_bulan_ini',
                'label' => 'Jumlah WUS baru, yang diukur LILA (Lingkar Lengan Atas) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3505,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3505 child
                'id' => 3557,
                'name' => 'jumlah_wus_baru_dengan_lila_23_5_cm_bulan_ini',
                'label' => 'Jumlah WUS baru, dengan LILA < 23,5 cm bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3505,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3558,
                'name' => 'jumlah_kunjungan_k1_bumil',
                'label' => 'Jumlah kunjungan K1 Bumil',
                'is_parent' => false,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3559,
                'name' => 'jumlah_kunjungan_bumil_lama',
                'label' => 'Jumlah kunjungan Bumil lama',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3559 child
                'id' => 3560,
                'name' => 'k2',
                'label' => 'K2',
                'is_parent' => false,
                'indicator_parent_id' => 3559,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3559 child
                'id' => 3561,
                'name' => 'k3',
                'label' => 'K3',
                'is_parent' => false,
                'indicator_parent_id' => 3559,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3559 child
                'id' => 3562,
                'name' => 'k4',
                'label' => 'K4',
                'is_parent' => false,
                'indicator_parent_id' => 3559,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3563,
                'name' => 'kunjungan_bumil_dengan_faktor_risiko',
                'label' => 'Kunjungan Bumil dengan faktor risiko :',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3564,
                'name' => 'a_20_th',
                'label' => 'a. < 20 th',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3565,
                'name' => 'b_35_th',
                'label' => 'b. > 35 th',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3566,
                'name' => 'c_spacing_2_th',
                'label' => 'c. Spacing < 2 th',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3567,
                'name' => 'd_paritas_5_th',
                'label' => 'd. Paritas > 5 th',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3568,
                'name' => 'e_hb_11_gram',
                'label' => 'e. HB 11 gram %',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3569,
                'name' => 'f_bb_kg_triwulan_III_45_kg',
                'label' => 'f. BB Kg Triwulan III < 45 Kg',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3570,
                'name' => 'g_tb_145_cm',
                'label' => 'g. TB < 145 cm',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3571,
                'name' => 'imunisasi_tt_bumil_tt1_tt2',
                'label' => 'Imunisasi TT Bumil (TT1, TT2) :',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3571 child
                'id' => 3572,
                'name' => 'a_tt1',
                'label' => 'a. TT1',
                'is_parent' => false,
                'indicator_parent_id' => 3571,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3571 child
                'id' => 3573,
                'name' => 'b_tt2',
                'label' => 'b. TT2',
                'is_parent' => false,
                'indicator_parent_id' => 3571,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3574,
                'name' => 'pemberian_tablet_fe_bumil',
                'label' => 'Pemberian tablet Fe Bumil :',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3574 child
                'id' => 3575,
                'name' => 'fe1',
                'label' => 'Fe1',
                'is_parent' => false,
                'indicator_parent_id' => 3574,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3574 child
                'id' => 3576,
                'name' => 'fe2',
                'label' => 'Fe2',
                'is_parent' => false,
                'indicator_parent_id' => 3574,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3574 child
                'id' => 3577,
                'name' => 'fe3',
                'label' => 'Fe3',
                'is_parent' => false,
                'indicator_parent_id' => 3574,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3578,
                'name' => 'jumlah_kesakitan_dan_kematian_bumil_yang_ditangani',
                'label' => 'Jumlah kesakitan dan kematian Bumil yang ditangani:',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3578 child
                'id' => 3579,
                'name' => 'a_pendarahan',
                'label' => 'a. Pendarahan',
                'is_parent' => false,
                'indicator_parent_id' => 3578,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3578 child
                'id' => 3580,
                'name' => 'b_infeksi_jalan_lahir',
                'label' => 'b. Infeksi jalan lahir',
                'is_parent' => false,
                'indicator_parent_id' => 3578,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3578 child
                'id' => 3581,
                'name' => 'c_preeklamasi_eklamsi',
                'label' => 'c. Preeklamasi/Eklamsi',
                'is_parent' => false,
                'indicator_parent_id' => 3578,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3578 child
                'id' => 3582,
                'name' => 'd_sebab_lain',
                'label' => 'd. Sebab lain',
                'is_parent' => false,
                'indicator_parent_id' => 3578,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3583,
                'name' => 'deteksi_resti_bumil_oleh_nakes',
                'label' => 'Deteksi resti bumil oleh nakes',
                'is_parent' => false,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3584,
                'name' => 'deteksi_resti_bumil_oleh_masyarakat',
                'label' => 'Deteksi resti bumil oleh masyarakat',
                'is_parent' => false,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3585,
                'name' => 'persalinan',
                'label' => 'Persalinan',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3586,
                'name' => 'a_20_tahun',
                'label' => 'a. < 20 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3587,
                'name' => 'b_20_24_tahun',
                'label' => 'b.  20 - 24 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3588,
                'name' => 'c_25_29_tahun',
                'label' => 'c. 25 - 29 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3589,
                'name' => 'd_30_34_tahun',
                'label' => 'd. 30 - 34 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3590,
                'name' => 'e_35_tahun',
                'label' => 'e. > 35 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3591,
                'name' => 'jumlah_persalinan_ditolong_oleh_nakes',
                'label' => 'Jumlah persalinan ditolong oleh Nakes',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3591 child
                'id' => 3592,
                'name' => 'lahir_hidup',
                'label' => 'Lahir hidup',
                'is_parent' => false,
                'indicator_parent_id' => 3591,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3591 child
                'id' => 3593,
                'name' => 'lahir_mati',
                'label' => 'Lahir mati',
                'is_parent' => false,
                'indicator_parent_id' => 3591,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3591 child
                'id' => 3594,
                'name' => 'bblr_bb_2500_gram',
                'label' => 'BBLR (BB < 2500 gram)',
                'is_parent' => false,
                'indicator_parent_id' => 3591,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3595,
                'name' => 'jumlah_persalinan_dukun_didampingi_oleh_nakes',
                'label' => 'Jumlah persalinan dukun didampingi oleh Nakes :',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        ];
    }
}
