<?php

use Illuminate\Database\Seeder;

class LB3ProductionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $parent = [
            [ // main parent
                'id' => 3500,
                'name' => 'kesehatan_ibu_dan_anak',
                'label' => 'Kesehatan Ibu Dan Anak',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // sub-parent
                'id' => 3501,
                'name' => 'kesehatan_ibu_dan_anak_gizi',
                'label' => 'Gizi',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3502,
                'name' => 'upaya_penanggulangan_anemia_gizi_besi_fe',
                'label' => 'Upaya Penanggulangan Anemia Gizi Besi (Fe)',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3503,
                'name' => 'upaya_pemantauan_pertumbuhan_balita',
                'label' => 'Upaya Pemantauan Pertumbuhan Balita',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3504,
                'name' => 'upaya_penanggulangan_gangguan_akibat_kekurangan_yodium_gaky',
                'label' => 'Upaya Penanggulangan Gangguan Akibat Kekurangan Yodium (GAKY)',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3505,
                'name' => 'upaya_penaggulangan_kekurangan_energi_kronis_kek',
                'label' => 'Upaya Penanggulangan Kekurangan Energi Kronis (KEK)',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3506,
                'name' => 'pelayanan_ibu_hamil',
                'label' => 'Pelayanan Ibu Hamil',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3507,
                'name' => 'pelayanan_persalinan',
                'label' => 'Pelayanan Persalinan',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3508,
                'name' => 'pelayanan_ibu_menyusui',
                'label' => ' Pelayanan Ibu Menyusui ',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3509,
                'name' => 'pelayanan_bayi',
                'label' => 'Pelayanan Bayi',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3510,
                'name' => 'pelayanan_anak_balita',
                'label' => 'Pelayanan Anak Balita',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3511,
                'name' => 'imunisasi',
                'label' => 'IMUNISASI',
                'is_parent' => true,
                'indicator_parent_id' => 3500,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3512,
                'name' => 'pengamatan_penyakit_menular',
                'label' => 'PENGAMATAN PENYAKIT MENULAR',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3513,
                'name' => 'acute_flaccid_paralysis_afp',
                'label' => 'Acute Flaccid Paralysis (AFP)',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3514,
                'name' => 'tetanus_neonatorum',
                'label' => 'Tetanus Neonatorum',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3515,
                'name' => 'malaria',
                'label' => 'Malaria',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3516,
                'name' => 'dbd_demam_berdarah_dengue',
                'label' => 'DBD (Demam Berdarah Dengue)',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3517,
                'name' => 'rabies',
                'label' => 'Rabies',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3518,
                'name' => 'filaria',
                'label' => 'Filaria',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3519,
                'name' => 'penyakit_zoonosis_lain_antraks',
                'label' => 'PENYAKIT ZOONOSIS LAIN (Antraks)',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3520,
                'name' => 'frambusia',
                'label' => 'Frambusia',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3521,
                'name' => 'diare',
                'label' => 'Diare',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3522,
                'name' => 'ispa',
                'label' => 'ISPA',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3523,
                'name' => 'tb_paru',
                'label' => 'TB Paru',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                'id' => 3524,
                'name' => 'kusta',
                'label' => 'Kusta',
                'is_parent' => true,
                'indicator_parent_id' => 3512,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3501 child
                'id' => 3525,
                'name' => 'upaya_penanggulangan_kekurangan_vitamin_a',
                'label' => 'Upaya Penanggulangan Kekurangan Vitamin A',
                'is_parent' => false,
                'indicator_parent_id' => 3501,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3501 child
                'id' => 3526,
                'name' => 'jumlah_anak_balita_1_5_th_dapat_kapsul_vit_a_dosis_tinggi_200000_IU_bulan_ini',
                'label' => 'Jumlah anak balita (1-5 th) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3501,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3501 child
                'id' => 3527,
                'name' => 'jumlah_ibu_nifas_sd_40_hr_dapat_kapsul_vit_a_dosis_tinggi_200000_iu_bulan_ini',
                'label' => 'Jumlah Ibu nifas (s/d 40 hr) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3501,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3501 child
                'id' => 3528,
                'name' => 'jumlah_bayi_6_11_th_dapat_kapsul_vit_a_dosis_tinggi_200000_iu_bulan_ini',
                'label' => 'Jumlah bayi (6-11 th) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3501,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3529,
                'name' => 'jumlah_ibu_hamil_dapat_tablet_tambah_darah_fe_30_tablet_fe1_bulan_ini',
                'label' => 'Jumlah Ibu hamil dapat tablet tambah darah (Fe) 30 tablet (Fe1) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3530,
                'name' => 'jumlah_ibu_hamil_dapat_tablet_tambah_darah_fe_90_tablet_fe2_bulan_ini',
                'label' => 'Jumlah Ibu hamil dapat tablet tambah darah (Fe) 90 tablet (Fe2) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3531,
                'name' => 'jumlah_balita_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah Balita diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3532,
                'name' => 'jumlah_balita_yang_diperiksa_dengan_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah Balita yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3533,
                'name' => 'jumlah_wus_15_45_th_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah WUS (15 - 45 th) diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3534,
                'name' => 'jumlah_wus_15_45_th_yang_diperiksa_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah WUS (15 - 45 th) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3535,
                'name' => 'jumlah_remaja_putri_14_18_th_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah Remaja Putri (14 - 18 th) diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3536,
                'name' => 'jumlah_remaja_putri_14_18_th_yang_diperiksa_dengan_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah Remaja Putri (14 - 18 th) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3537,
                'name' => 'jumlah_tenaga_kerja_wanita_nakerwan_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah Tenaga Kerja Wanita (nakerwan) diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3538,
                'name' => 'jumlah_tenaga_kerja_wanita_nakerwan_yang_diperiksa_dengan_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah Tenaga Kerja Wanita (nakerwan) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3539,
                'name' => 'jumlah_ibu_hamil_diperiksa_status_anemia_bulan_ini',
                'label' => 'Jumlah Ibu hamil diperiksa status anemia bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3502 child
                'id' => 3540,
                'name' => 'jumlah_ibu_hamil_yang_diperiksa_dengan_status_anemia_11_gr_bulan_ini',
                'label' => 'Jumlah Ibu hamil yang diperiksa dengan status anemia < 11 gr % bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3502,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3541,
                'name' => 'jumlah_balita_yang_ada_bulan_ini',
                'label' => 'Jumlah Balita yang ada bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3542,
                'name' => 'jumlah_balita_yang_mempunyai_kms_bulan_ini',
                'label' => 'Jumlah Balita yang mempunyai KMS bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3543,
                'name' => 'jumlah_balita_yang_naik_berat_badannya_bulan_ini',
                'label' => 'Jumlah Balita yang Naik berat badannya bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3544,
                'name' => 'jumlah_balita_yang_tidak_naik_tetap_berat_badannya_bulan_ini',
                'label' => 'Jumlah Balita yang Tidak naik/tetap berat badannya bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3545,
                'name' => 'jumlah_balita_yang_ditimbang_bulan_ini_tetapi_tidak_ditimbang_bulan_lalu',
                'label' => 'Jumlah Balita yang ditimbang bulan ini tetapi tidak ditimbang bulan lalu',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3546,
                'name' => 'jumlah_balita_yang_baru_ditimbang_bulan_ini',
                'label' => 'Jumlah Balita yang Baru ditimbang bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3547,
                'name' => 'jumlah_balita_yang_dapat_ditimbang_bulan_ini',
                'label' => 'Jumlah Balita yang dapat ditimbang bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3548,
                'name' => 'jumlah_balita_yang_tidak_dapat_ditimbang_bulan_ini',
                'label' => 'Jumlah Balita yang tidak dapat ditimbang bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3549,
                'name' => 'jumlah_balita_dengan_berat_badan_di_bawah_garis_merah_bgm_bulan_ini',
                'label' => 'Jumlah Balita dengan Berat badan di Bawah Garis Merah (BGM) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3503 child
                'id' => 3550,
                'name' => 'jumlah_balita_gizi_buruk_bulan_ini',
                'label' => 'Jumlah Balita gizi buruk bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3503,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3504 child
                'id' => 3551,
                'name' => 'jumlah_penderita_gaky_laki_laki_bulan_ini',
                'label' => 'Jumlah penderita GAKY laki-laki bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3504,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3504 child
                'id' => 3552,
                'name' => 'jumlah_penderita_gaky_perempuan_bulan_ini',
                'label' => 'Jumlah penderita GAKY perempuan bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3504,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3504 child
                'id' => 3553,
                'name' => 'jumlah_ibu_hamil_mendapat_kapsul_yodium',
                'label' => 'Jumlah ibu hamil mendapat kapsul yodium',
                'is_parent' => false,
                'indicator_parent_id' => 3504,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3504 child
                'id' => 3554,
                'name' => 'jumlah_penduduk_lainnya_mendapat_kapsul_yodium',
                'label' => 'Jumlah penduduk lainnya mendapat kapsul yodium',
                'is_parent' => false,
                'indicator_parent_id' => 3504,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3505 child
                'id' => 3555,
                'name' => 'jumlah_ibu_hamil_baru_diukur_lila_lingkar_lengan_atas_bulan_ini',
                'label' => 'Jumlah Ibu hamil baru, diukur LILA (Lingkar Lengan Atas) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3505,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3505 child
                'id' => 3556,
                'name' => 'jumlah_ibu_hamil_baru_dengan_lila_23_5_cm_bulan_ini',
                'label' => 'Jumlah Ibu hamil baru, dengan LILA < 23,5 cm bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3505,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3505 child
                'id' => 3556,
                'name' => 'jumlah_wus_baru_yang_diukur_lila_lingkar_lengan_atas_bulan_ini',
                'label' => 'Jumlah WUS baru, yang diukur LILA (Lingkar Lengan Atas) bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3505,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3505 child
                'id' => 3557,
                'name' => 'jumlah_wus_baru_dengan_lila_23_5_cm_bulan_ini',
                'label' => 'Jumlah WUS baru, dengan LILA < 23,5 cm bulan ini',
                'is_parent' => false,
                'indicator_parent_id' => 3505,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3558,
                'name' => 'jumlah_kunjungan_k1_bumil',
                'label' => 'Jumlah kunjungan K1 Bumil',
                'is_parent' => false,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3559,
                'name' => 'jumlah_kunjungan_bumil_lama',
                'label' => 'Jumlah kunjungan Bumil lama',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3559 child
                'id' => 3560,
                'name' => 'k2',
                'label' => 'K2',
                'is_parent' => false,
                'indicator_parent_id' => 3559,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3559 child
                'id' => 3561,
                'name' => 'k3',
                'label' => 'K3',
                'is_parent' => false,
                'indicator_parent_id' => 3559,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3559 child
                'id' => 3562,
                'name' => 'k4',
                'label' => 'K4',
                'is_parent' => false,
                'indicator_parent_id' => 3559,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3563,
                'name' => 'kunjungan_bumil_dengan_faktor_risiko',
                'label' => 'Kunjungan Bumil dengan faktor risiko :',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3564,
                'name' => 'a_20_th',
                'label' => 'a. < 20 th',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3565,
                'name' => 'b_35_th',
                'label' => 'b. > 35 th',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3566,
                'name' => 'c_spacing_2_th',
                'label' => 'c. Spacing < 2 th',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3567,
                'name' => 'd_paritas_5_th',
                'label' => 'd. Paritas > 5 th',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3568,
                'name' => 'e_hb_11_gram',
                'label' => 'e. HB 11 gram %',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3569,
                'name' => 'f_bb_kg_triwulan_III_45_kg',
                'label' => 'f. BB Kg Triwulan III < 45 Kg',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3563 child
                'id' => 3570,
                'name' => 'g_tb_145_cm',
                'label' => 'g. TB < 145 cm',
                'is_parent' => false,
                'indicator_parent_id' => 3563,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3571,
                'name' => 'imunisasi_tt_bumil_tt1_tt2',
                'label' => 'Imunisasi TT Bumil (TT1, TT2) :',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3571 child
                'id' => 3572,
                'name' => 'a_tt1',
                'label' => 'a. TT1',
                'is_parent' => false,
                'indicator_parent_id' => 3571,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3571 child
                'id' => 3573,
                'name' => 'b_tt2',
                'label' => 'b. TT2',
                'is_parent' => false,
                'indicator_parent_id' => 3571,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3574,
                'name' => 'pemberian_tablet_fe_bumil',
                'label' => 'Pemberian tablet Fe Bumil :',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3574 child
                'id' => 3575,
                'name' => 'fe1',
                'label' => 'Fe1',
                'is_parent' => false,
                'indicator_parent_id' => 3574,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3574 child
                'id' => 3576,
                'name' => 'fe2',
                'label' => 'Fe2',
                'is_parent' => false,
                'indicator_parent_id' => 3574,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3574 child
                'id' => 3577,
                'name' => 'fe3',
                'label' => 'Fe3',
                'is_parent' => false,
                'indicator_parent_id' => 3574,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3578,
                'name' => 'jumlah_kesakitan_dan_kematian_bumil_yang_ditangani',
                'label' => 'Jumlah kesakitan dan kematian Bumil yang ditangani:',
                'is_parent' => true,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3578 child
                'id' => 3579,
                'name' => 'a_pendarahan',
                'label' => 'a. Pendarahan',
                'is_parent' => false,
                'indicator_parent_id' => 3578,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3578 child
                'id' => 3580,
                'name' => 'b_infeksi_jalan_lahir',
                'label' => 'b. Infeksi jalan lahir',
                'is_parent' => false,
                'indicator_parent_id' => 3578,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3578 child
                'id' => 3581,
                'name' => 'c_preeklamasi_eklamsi',
                'label' => 'c. Preeklamasi/Eklamsi',
                'is_parent' => false,
                'indicator_parent_id' => 3578,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3578 child
                'id' => 3582,
                'name' => 'd_sebab_lain',
                'label' => 'd. Sebab lain',
                'is_parent' => false,
                'indicator_parent_id' => 3578,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3583,
                'name' => 'deteksi_resti_bumil_oleh_nakes',
                'label' => 'Deteksi resti bumil oleh nakes',
                'is_parent' => false,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3506 child
                'id' => 3584,
                'name' => 'deteksi_resti_bumil_oleh_masyarakat',
                'label' => 'Deteksi resti bumil oleh masyarakat',
                'is_parent' => false,
                'indicator_parent_id' => 3506,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3585,
                'name' => 'persalinan',
                'label' => 'Persalinan',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3586,
                'name' => 'a_20_tahun',
                'label' => 'a. < 20 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3587,
                'name' => 'b_20_24_tahun',
                'label' => 'b.  20 - 24 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3588,
                'name' => 'c_25_29_tahun',
                'label' => 'c. 25 - 29 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3589,
                'name' => 'd_30_34_tahun',
                'label' => 'd. 30 - 34 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3585 child
                'id' => 3590,
                'name' => 'e_35_tahun',
                'label' => 'e. > 35 tahun',
                'is_parent' => false,
                'indicator_parent_id' => 3585,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3591,
                'name' => 'jumlah_persalinan_ditolong_oleh_nakes',
                'label' => 'Jumlah persalinan ditolong oleh Nakes',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3591 child
                'id' => 3592,
                'name' => 'lahir_hidup',
                'label' => 'Lahir hidup',
                'is_parent' => false,
                'indicator_parent_id' => 3591,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3591 child
                'id' => 3593,
                'name' => 'lahir_mati',
                'label' => 'Lahir mati',
                'is_parent' => false,
                'indicator_parent_id' => 3591,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3591 child
                'id' => 3594,
                'name' => 'bblr_bb_2500_gram',
                'label' => 'BBLR (BB < 2500 gram)',
                'is_parent' => false,
                'indicator_parent_id' => 3591,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3595,
                'name' => 'jumlah_persalinan_dukun_didampingi_oleh_nakes',
                'label' => 'Jumlah persalinan dukun didampingi oleh Nakes :',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3595 child
                'id' => 3596,
                'name' => 'jumlah_persalinan_dukun_didampingi_oleh_nakes',
                'label' => 'Jumlah persalinan dukun didampingi oleh Nakes :',
                'is_parent' => false,
                'indicator_parent_id' => 3595,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3595 child
                'id' => 3597,
                'name' => 'persalinan_dukun_didampingi_oleh_nakes_lahir_hidup',
                'label' => 'Lahir hidup',
                'is_parent' => false,
                'indicator_parent_id' => 3595,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3595 child
                'id' => 3598,
                'name' => 'persalinan_dukun_didampingi_oleh_nakes_lahir_mati',
                'label' => 'Lahir mati',
                'is_parent' => false,
                'indicator_parent_id' => 3595,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3595 child
                'id' => 3599,
                'name' => 'persalinan_dukun_didampingi_oleh_nakes_bblr__bb_2500_gram',
                'label' => 'BBLR (BB < 2500 gram)',
                'is_parent' => false,
                'indicator_parent_id' => 3595,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3600,
                'name' => 'jumlah_persalinan_ditolong_oleh_dukun_terlatih_tidak_terlatih',
                'label' => 'Jumlah persalinan ditolong oleh dukun terlatih/tidak telatih:',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3600 child
                'id' => 3601,
                'name' => 'persalinan_ditolong_oleh_dukun_terlatih_tidak_terlatih_lahir_hidup',
                'label' => 'Lahir hidup',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3600 child
                'id' => 3602,
                'name' => 'persalinan_ditolong_oleh_dukun_terlatih_tidak_terlatih_lahir_mati',
                'label' => 'Lahir mati',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3600 child
                'id' => 3603,
                'name' => 'persalinan_dukun_didampingi_oleh_nakes_bblr__bb_2500_gram',
                'label' => 'BBLR (BB < 2500 gram)',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3604,
                'name' => 'kunjungan_neonatus',
                'label' => 'Kunjungan Neonatus',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3604 child
                'id' => 3605,
                'name' => 'kunjungan_neonatus_0_7_hari',
                'label' => '0 - 7 hari',
                'is_parent' => false,
                'indicator_parent_id' => 3604,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3604 child
                'id' => 3606,
                'name' => 'kunjungan_neonatus_7_28_hari',
                'label' => '7 - 28 hari',
                'is_parent' => false,
                'indicator_parent_id' => 3604,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3607,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_bersalin_ditangani',
                'label' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 child
                'id' => 3608,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_bersalin_ditangani_pendarahan',
                'label' => 'Pendarahan',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 child
                'id' => 3609,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_bersalin_ditangani_infeksi_jalan_lahir',
                'label' => 'Infeksi Jalan Lahir',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 child
                'id' => 3610,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_bersalin_ditangani_preeklamsi_eklamsi',
                'label' => 'Preeklamsi / Eklamsi',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 child
                'id' => 3611,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_bersalin_ditangani_sebab_lain',
                'label' => 'Sebab lain',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3507 child
                'id' => 3612,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_nifas_ditangani',
                'label' => 'Jumlah kesakitan dan kematian ibu nifas ditangani',
                'is_parent' => true,
                'indicator_parent_id' => 3507,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3612 child
                'id' => 3613,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_nifas_pendarahan',
                'label' => 'Pendarahan',
                'is_parent' => false,
                'indicator_parent_id' => 3612,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3612 child
                'id' => 3614,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_nifas_infeksi_jalan_lahir',
                'label' => 'Infeksi jalan lahir',
                'is_parent' => false,
                'indicator_parent_id' => 3612,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3612 child
                'id' => 3615,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_nifas_preeklamsi_eklamsi',
                'label' => 'Preeklamsi/Eklamsi',
                'is_parent' => false,
                'indicator_parent_id' => 3612,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3612 child
                'id' => 3616,
                'name' => 'jumlah_kesakitan_dan_kematian_ibu_nifas_sebab_lain',
                'label' => 'Sebab lain',
                'is_parent' => false,
                'indicator_parent_id' => 3612,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3508 child
                'id' => 3617,
                'name' => 'pelayanan_ibu_menyusui_kunjungan_baru',
                'label' => 'Kunjungan baru',
                'is_parent' => false,
                'indicator_parent_id' => 3508,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3508 child
                'id' => 3618,
                'name' => 'pelayanan_ibu_menyusui_kunjungan_lama',
                'label' => 'Kunjungan lama',
                'is_parent' => false,
                'indicator_parent_id' => 3508,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3508 child
                'id' => 3619,
                'name' => 'pelayanan_ibu_menyusui_akseptor_baru_buteki',
                'label' => 'Akseptor baru Buteki',
                'is_parent' => false,
                'indicator_parent_id' => 3508,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3508 child
                'id' => 3620,
                'name' => 'pelayanan_ibu_menyusui_akseptor_aktif_buteki',
                'label' => 'Akseptor aktif Buteki',
                'is_parent' => false,
                'indicator_parent_id' => 3508,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3508 child
                'id' => 3621,
                'name' => 'pelayanan_ibu_menyusui_akseptor_aktif_buteki',
                'label' => 'Akseptor aktif Buteki',
                'is_parent' => false,
                'indicator_parent_id' => 3508,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3508 child
                'id' => 3622,
                'name' => 'pelayanan_ibu_menyusui_buteki_dapat_fe',
                'label' => 'Buteki dapat Fe',
                'is_parent' => false,
                'indicator_parent_id' => 3508,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3508 child
                'id' => 3623,
                'name' => 'pelayanan_ibu_menyusui_buteki_dapat_vitamin_a_dosis_tinggi',
                'label' => 'Buteki dapat Vitamin A dosis tinggi',
                'is_parent' => false,
                'indicator_parent_id' => 3508,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3508 child
                'id' => 3624,
                'name' => 'pelayanan_ibu_menyusui_buteki_asi_ekslusif_0_6_bulan',
                'label' => 'ASI Eksklusif 0 - 6 bulan',
                'is_parent' => false,
                'indicator_parent_id' => 3508,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3509 child
                'id' => 3625,
                'name' => 'pelayanan_bayi_kunjungan_baru_diperiksa',
                'label' => 'Kunjungan baru diperiksa',
                'is_parent' => false,
                'indicator_parent_id' => 3509,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3509 child
                'id' => 3626,
                'name' => 'pelayanan_bayi_kunjungan_baru_dirujuk',
                'label' => 'Kunjungan baru dirujuk',
                'is_parent' => false,
                'indicator_parent_id' => 3509,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3509 child
                'id' => 3627,
                'name' => 'pelayanan_bayi_kunjungan_lama_diperiksa',
                'label' => 'Kunjungan lama diperiksa',
                'is_parent' => false,
                'indicator_parent_id' => 3509,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3509 child
                'id' => 3628,
                'name' => 'pelayanan_bayi_kunjungan_lama_dirujuk',
                'label' => 'Kunjungan lama dirujuk',
                'is_parent' => false,
                'indicator_parent_id' => 3509,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3509 child
                'id' => 3629,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_0_7_hari',
                'label' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari)',
                'is_parent' => true,
                'indicator_parent_id' => 3509,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3629 child
                'id' => 3630,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_0_7_hari_bblr',
                'label' => 'BBLR',
                'is_parent' => false,
                'indicator_parent_id' => 3629,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3629 child
                'id' => 3631,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_0_7_hari_tetanus_neonatorum',
                'label' => 'Tetanus Neonatorum',
                'is_parent' => false,
                'indicator_parent_id' => 3629,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3629 child
                'id' => 3632,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_0_7_hari_bblr_dirujuk_ke_rsu',
                'label' => 'BBLR dirujuk ke RSU',
                'is_parent' => false,
                'indicator_parent_id' => 3629,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3629 child
                'id' => 3633,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_0_7_hari_tetanus_neonatorum_dirujuk_ke_rsu',
                'label' => 'Tetanus Neonatorum dirujuk ke RSU',
                'is_parent' => false,
                'indicator_parent_id' => 3629,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3629 child
                'id' => 3634,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_0_7_hari_oleh_sebab_lain',
                'label' => 'Oleh sebab lain',
                'is_parent' => false,
                'indicator_parent_id' => 3629,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3509 child
                'id' => 3635,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_8_28_hari',
                'label' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari)',
                'is_parent' => true,
                'indicator_parent_id' => 3509,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3635 child
                'id' => 3636,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_8_28_hari_bblr',
                'label' => 'BBLR',
                'is_parent' => false,
                'indicator_parent_id' => 3635,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3635 child
                'id' => 3637,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_8_28_hari_tetanus_neonatorum',
                'label' => 'Tetanus Neonatorum',
                'is_parent' => false,
                'indicator_parent_id' => 3635,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3635 child
                'id' => 3638,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_8_28_hari_bblr_dirujuk_ke_rsu',
                'label' => 'BBLR dirujuk ke RSU',
                'is_parent' => false,
                'indicator_parent_id' => 3635,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3635 child
                'id' => 3639,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_8_28_hari_tetanus_neonatorum_dirujuk_ke_rsu',
                'label' => 'Tetanus Nenonatorum dirujuk ke RSU',
                'is_parent' => false,
                'indicator_parent_id' => 3635,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3635 child
                'id' => 3639,
                'name' => 'pelayanan_bayi_jumlah_kesakitan_dan_kematian_perinatal_8_28_hari_oleh_sebab_lain',
                'label' => 'Oleh sebab lain',
                'is_parent' => false,
                'indicator_parent_id' => 3635,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3509 child
                'id' => 3640,
                'name' => 'jumlah_kesakitan_dan_kematian_perinatal_28_hari_1_tahun',
                'label' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun)',
                'is_parent' => true,
                'indicator_parent_id' => 3509,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3640 child
                'id' => 3641,
                'name' => 'jumlah_kesakitan_dan_kematian_perinatal_28_hari_1_tahun_bblr',
                'label' => 'BBLR',
                'is_parent' => false,
                'indicator_parent_id' => 3640,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3640 child
                'id' => 3642,
                'name' => 'jumlah_kesakitan_dan_kematian_perinatal_28_hari_1_tahun_teteanus_neonatorum',
                'label' => 'Tetanus Neonatorum',
                'is_parent' => false,
                'indicator_parent_id' => 3640,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3640 child
                'id' => 3643,
                'name' => 'jumlah_kesakitan_dan_kematian_perinatal_28_hari_1_tahun_bblr_dirujuk_ke_rsu',
                'label' => 'BBLR dirujuk ke RSU',
                'is_parent' => false,
                'indicator_parent_id' => 3640,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3640 child
                'id' => 3644,
                'name' => 'jumlah_kesakitan_dan_kematian_perinatal_28_hari_1_tahun_tetanus_neonatorum_dirujuk_ke_rsu',
                'label' => 'Tetanus Neonatorum dirujuk ke RSU',
                'is_parent' => false,
                'indicator_parent_id' => 3640,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3640 child
                'id' => 3645,
                'name' => 'jumlah_kesakitan_dan_kematian_perinatal_28_hari_1_tahun_oleh_sebab_lain',
                'label' => 'Oleh sebab lain',
                'is_parent' => false,
                'indicator_parent_id' => 3640,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3510 child
                'id' => 3646,
                'name' => 'pelayanan_anak_balita_kunjungan_baru_diperiksa',
                'label' => 'Kunjungan baru diperiksa',
                'is_parent' => false,
                'indicator_parent_id' => 3510,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3510 child
                'id' => 3647,
                'name' => 'pelayanan_anak_balita_kunjungan_baru_dirujuk',
                'label' => 'Kunjungan baru dirujuk',
                'is_parent' => false,
                'indicator_parent_id' => 3510,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3510 child
                'id' => 3648,
                'name' => 'pelayanan_anak_balita_kunjungan_lama_diperiksa',
                'label' => 'Kunjungan lama diperiksa',
                'is_parent' => false,
                'indicator_parent_id' => 3510,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3510 child
                'id' => 3649,
                'name' => 'pelayanan_anak_balita_kunjungan_lama_dirujuk',
                'label' => 'Kunjungan lama dirujuk',
                'is_parent' => false,
                'indicator_parent_id' => 3510,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3510 child
                'id' => 3650,
                'name' => 'pelayanan_anak_balita_jumlah_kesakitan_dan_kematian_anak_balita',
                'label' => 'Jumlah kesakitan dan kematian anak balita',
                'is_parent' => false,
                'indicator_parent_id' => 3510,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3651,
                'name' => 'imunisasi_jumlah_bayi_divaksinasi_campak',
                'label' => 'Jumlah bayi divaksinasi campak',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3652,
                'name' => 'imunisasi_jumlah_bayi_divaksinasi_dpt_i',
                'label' => 'Jumlah bayi divaksinasi DPT I',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3653,
                'name' => 'imunisasi_jumlah_bayi_0_7_hari_divaksinasi_hepatitis_b',
                'label' => 'Jumlah bayi 0 - 7 hari divaksinasi hepatitis B',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3654,
                'name' => 'imunisasi_jumlah_bayi_gt_7_hari_divaksinasi_hepatitis_b',
                'label' => 'Jumlah bayi > 7 hari divaksinasi hepatitis B',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3655,
                'name' => 'imunisasi_jumlah_ibu_hamil_divaksinasi_tt_i',
                'label' => 'Jumlah Ibu Hamil divaksinasi TT I',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3656,
                'name' => 'imunisasi_jumlah_ibu_hamil_divaksinasi_tt_ii',
                'label' => 'Jumlah Ibu Hamil divaksinasi TT II',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3657,
                'name' => 'imunisasi_jumlah_ibu_hamil_divaksinasi_tt_boster',
                'label' => 'Jumlah Ibu Hamil divaksinasi TT Boster',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3658,
                'name' => 'imunisasi_jumlah_wanita_usia_subur_calon_pengantin_wus_divaksinasi_tt_i',
                'label' => 'Jumlah wanita usia subur/calon pengantin (WUS), divaksinasi TT I',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3659,
                'name' => 'imunisasi_jumlah_murid_sd_kelas_i_divaksinasi_dp',
                'label' => 'Jumlah murid SD kelas I divaksinasi DP',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3660,
                'name' => 'imunisasi_jumlah_murid_sd_kelas_ii_dan_iii_divaksinasi_tt',
                'label' => 'Jumlah murid SD kelas II dan III divaksinasi TT',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3511 child
                'id' => 3661,
                'name' => 'imunisasi_jumlah_bayi_divaksinasi_bcg',
                'label' => 'Jumlah bayi divaksinasi BCG',
                'is_parent' => false,
                'indicator_parent_id' => 3511,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3513 child
                'id' => 3662,
                'name' => 'afp_jumlah_kasus_afp_baru_0_15_tahun_ditemukan',
                'label' => 'Jumlah kasus AFP baru (0 - 15 tahun) ditemukan',
                'is_parent' => false,
                'indicator_parent_id' => 3513,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3513 child
                'id' => 3663,
                'name' => 'afp_jumlah_kasus_tetanus_neonatorum_ditemukan',
                'label' => 'Jumlah kasus tetanus neonatorum ditemukan',
                'is_parent' => false,
                'indicator_parent_id' => 3513,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3514 child
                'id' => 3664,
                'name' => 'tn_jumlah_kasus_tetanus_neonatorum_ditemukan',
                'label' => 'Jumlah kasus tetanus neonatorum ditemukan',
                'is_parent' => false,
                'indicator_parent_id' => 3514,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3514 child
                'id' => 3665,
                'name' => 'tn_jumlah_kasus_tetanus_neonatorum_dilacak',
                'label' => 'Jumlah kasus tetanus neonatorum dilacak',
                'is_parent' => false,
                'indicator_parent_id' => 3514,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3515 child
                'id' => 3665,
                'name' => 'malaria_jumlah_penderita_malaria_berat_dan_komplikasi',
                'label' => 'Jumlah penderita malaria berat dan komplikasi',
                'is_parent' => false,
                'indicator_parent_id' => 3515,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3515 child
                'id' => 3666,
                'name' => 'malaria_jumlah_bumil_yang_memperoleh_pengobatan_profilaksis_pencegahan',
                'label' => 'Jumlah Bumil yang memperoleh pengobatan profilaksis/pencegahan',
                'is_parent' => false,
                'indicator_parent_id' => 3515,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3515 child
                'id' => 3667,
                'name' => 'malaria_jumlah_rumah_yang_disemprot',
                'label' => 'Jumlah rumah yang disemprot',
                'is_parent' => false,
                'indicator_parent_id' => 3515,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3515 child
                'id' => 3668,
                'name' => 'malaria_jumlah_penderita_malaria_klinis',
                'label' => 'Jumlah penderita malaria klinis',
                'is_parent' => false,
                'indicator_parent_id' => 3515,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3515 child
                'id' => 3669,
                'name' => 'malaria_jumlah_penderita_pemeriksaan_lab',
                'label' => 'Jumlah penderita pemeriksaan lab',
                'is_parent' => false,
                'indicator_parent_id' => 3515,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3516 child
                'id' => 3670,
                'name' => 'dbd_jumlah_pelacakan_penderita_dbd',
                'label' => 'Jumlah pelacakan penderita DBD',
                'is_parent' => false,
                'indicator_parent_id' => 3516,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3516 child
                'id' => 3671,
                'name' => 'dbd_jumlah_fogging_fokus',
                'label' => 'Jumlah fogging fokus',
                'is_parent' => false,
                'indicator_parent_id' => 3516,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3516 child
                'id' => 3672,
                'name' => 'dbd_jumlah_desa_kelurahan_diabatisasi_selektif',
                'label' => 'Jumlah desa/kelurahan diabatisasi selektif',
                'is_parent' => false,
                'indicator_parent_id' => 3516,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3516 child
                'id' => 3673,
                'name' => 'dbd_jumlah_desa_kelurahan_dilakukan_pemberantasan_sarang_nyamuk',
                'label' => 'Jumlah desa/kelurahan dilakukan Pemberantasan Sarang Nyamuk',
                'is_parent' => false,
                'indicator_parent_id' => 3516,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3516 child
                'id' => 3674,
                'name' => 'dbd_jumlah_rumah_yang_dilakukan_pemeriksaan_jentik',
                'label' => 'Jumlah rumah yang dilakukan pemeriksaan jentik',
                'is_parent' => false,
                'indicator_parent_id' => 3516,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3516 child
                'id' => 3675,
                'name' => 'dbd_jumlah_rumah_yang_ada_jentik',
                'label' => 'Jumlah rumah yang ada jentik',
                'is_parent' => false,
                'indicator_parent_id' => 3516,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3517 child
                'id' => 3676,
                'name' => 'rabies_jumlah_penderita_digigit_oleh_hewan_penular_rabies',
                'label' => 'Jumlah penderita digigit oleh hewan penular rabies',
                'is_parent' => false,
                'indicator_parent_id' => 3517,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3517 child
                'id' => 3677,
                'name' => 'rabies_jumlah_penderita_gigitan_yang_divaksin_anti_rabies_var_atau_varplus_serum_anti_rabies_sar',
                'label' => 'Jumlah penderita gigitan yg di Vaksin Anti Rabies (VAR) atau VAR (+) Serum Anti Rabies (SAR)',
                'is_parent' => false,
                'indicator_parent_id' => 3517,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3518 child
                'id' => 3678,
                'name' => 'filaria_jumlah_desa_endemis',
                'label' => 'Jumlah desa endemis',
                'is_parent' => false,
                'indicator_parent_id' => 3518,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3518 child
                'id' => 3679,
                'name' => 'filaria_jumlah_desa_dengan_cakupan_pengobatan_massal_gt_80',
                'label' => 'Jumlah desa dengan cakupan pengobatan massal > 80 %',
                'is_parent' => false,
                'indicator_parent_id' => 3518,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3519 child
                'id' => 3680,
                'name' => 'antraks_jumlah_yang_diobati',
                'label' => 'Jumlah yang diobati',
                'is_parent' => false,
                'indicator_parent_id' => 3519,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3520 child
                'id' => 3681,
                'name' => 'frambusia_jumlah_penduduk_0_14_tahun_yang_diperiksa_untuk_frambusia',
                'label' => 'Jumlah penduduk 0 - 14 tahun yang diperiksa untuk Frambusia',
                'is_parent' => false,
                'indicator_parent_id' => 3520,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3520 child
                'id' => 3682,
                'name' => 'frambusia_jumlah_penderita_frambusia_yang_ditemukan',
                'label' => 'Jumlah penderita Frambusia yang ditemukan',
                'is_parent' => false,
                'indicator_parent_id' => 3520,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3520 child
                'id' => 3683,
                'name' => 'frambusia_jumlah_penderita_kontak_penderita_yang_diobati',
                'label' => 'Jumlah penderita/kontak penderita yang diobati',
                'is_parent' => false,
                'indicator_parent_id' => 3520,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3521 child
                'id' => 3684,
                'name' => 'diare_jumlah_penderita_diare_termasuk_tersangka_kolera_disentri_dapat_oralit',
                'label' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat oralit',
                'is_parent' => false,
                'indicator_parent_id' => 3521,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3521 child
                'id' => 3685,
                'name' => 'diare_jumlah_penderita_diare_termasuk_tersangka_kolera_disentri_dapat_infus',
                'label' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat infus',
                'is_parent' => false,
                'indicator_parent_id' => 3521,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3521 child
                'id' => 3686,
                'name' => 'diare_jumlah_penderita_diare_termasuk_tersangka_kolera_disentri_dapat_antibiotik',
                'label' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat antibiotik',
                'is_parent' => false,
                'indicator_parent_id' => 3521,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3522 child
                'id' => 3687,
                'name' => 'ispa_jumlah_penderita_pneumonia',
                'label' => 'Jumlah penderita Pneumonia',
                'is_parent' => false,
                'indicator_parent_id' => 3522,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3522 child
                'id' => 3688,
                'name' => 'ispa_jumlah_penderita_pneumonia_balita_dirujuk_ke_dokter',
                'label' => 'Jumlah penderita Pneumonia balita dirujuk ke dokter',
                'is_parent' => false,
                'indicator_parent_id' => 3522,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3523 child
                'id' => 3689,
                'name' => 'tb_jumlah_penderita_bta_positif_baru_diobati',
                'label' => 'Jumlah penderita BTA positif baru diobati',
                'is_parent' => false,
                'indicator_parent_id' => 3523,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3523 child
                'id' => 3690,
                'name' => 'tb_jumlah_penderita_bta_negatif_dan_dengan_ronsen_positif_diobati',
                'label' => 'Jumlah penderita BTA negatif dan dengan Ronsen (+) diobati',
                'is_parent' => false,
                'indicator_parent_id' => 3523,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3523 child
                'id' => 3691,
                'name' => 'tb_jumlah_penderita_mengikuti_pengobatan_lengkap',
                'label' => 'Jumlah penderita mengikuti pengobatan lengkap',
                'is_parent' => false,
                'indicator_parent_id' => 3523,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3523 child
                'id' => 3692,
                'name' => 'tb_jumlah_penderita_tb_paru_yang_sembuh',
                'label' => 'Jumlah penderita TB Paru yang sembuh',
                'is_parent' => false,
                'indicator_parent_id' => 3523,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3523 child
                'id' => 3693,
                'name' => 'tb_jumlah_penderita_kambuh',
                'label' => 'Jumlah penderita kambuh',
                'is_parent' => false,
                'indicator_parent_id' => 3523,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3524 child
                'id' => 3694,
                'name' => 'kusta_jumlah_penderita_terdaftar_pb_pausibasiler_mb_multibasiler',
                'label' => 'Jumlah penderita terdaftar (PB/Pausibasiler + MB/Multibasiler)',
                'is_parent' => false,
                'indicator_parent_id' => 3524,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3524 child
                'id' => 3695,
                'name' => 'kusta_jumlah_penderita_baru_yang_ditemukan',
                'label' => 'Jumlah penderita baru yang ditemukan',
                'is_parent' => false,
                'indicator_parent_id' => 3524,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3524 child
                'id' => 3696,
                'name' => 'kusta_jumlah_penderita_mb_diantara_kasus_baru',
                'label' => 'Jumlah penderita MB di antara kasus baru',
                'is_parent' => false,
                'indicator_parent_id' => 3524,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3524 child
                'id' => 3697,
                'name' => 'kusta_jumlah_penderita_baru_menurut_cacat_tingkat_ii',
                'label' => 'Jumlah penderita baru menurut cacat tingkat II',
                'is_parent' => false,
                'indicator_parent_id' => 3524,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3524 child
                'id' => 3698,
                'name' => 'kusta_jumlah_penderita_mb_yang_mendapat_pengobatan_mdt',
                'label' => 'Jumlah penderita MB yang mendapat pengobatan MDT',
                'is_parent' => false,
                'indicator_parent_id' => 3524,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3524 child
                'id' => 3699,
                'name' => 'kusta_jumlah_penderita_pb_yang_mendapat_pengobatan_mdt',
                'label' => 'Jumlah penderita PB yang mendapat pengobatan MDT',
                'is_parent' => false,
                'indicator_parent_id' => 3524,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3524 child
                'id' => 3670,
                'name' => 'kusta_jumlah_penderita_mb_yang_mendapat_pengobatan_mdt_komplit_rtf',
                'label' => 'Jumlah penderita MB yang mendapat pengobatan MDT komplit (RFT)',
                'is_parent' => false,
                'indicator_parent_id' => 3524,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3524 child
                'id' => 3671,
                'name' => 'kusta_jumlah_penderita_pb_yang_mendapat_pengobatan_mdt_komplit_rtf',
                'label' => 'Jumlah penderita PB yang mendapat pengobatan MDT komplit (RFT)',
                'is_parent' => false,
                'indicator_parent_id' => 3524,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
        ];
    }
}
