<?php

use Illuminate\Database\Seeder;

class LB3Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('indicator')->insert(
            [
                [
                    // 'id' => 1,
                    // 'category_id' => 18,
                    'name' => 'Upaya Penanggulangan Kekurangan Vitamin A',
                    'label' => 'Upaya Penanggulangan Kekurangan Vitamin A',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 2,
                    // 'category_id' => 18
                    'name' => 'Jumlah anak balita (1-5 th) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                    'label' => 'Jumlah anak balita (1-5 th) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 3,
                    // 'category_id' => 18,
                    'name' => 'Jumlah Ibu nifas (s/d 40 hr) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                    'label' => 'Jumlah Ibu nifas (s/d 40 hr) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 4,
                    // 'category_id' => 18,
                    'name' => 'Jumlah bayi (6-11 bl) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                    'label' => 'Jumlah bayi (6-11 bl) dapat kapsul vit. A dosis tinggi (200.000 IU) bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 5,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Ibu hamil dapat tablet tambah darah (Fe) 30 tablet (Fe1) bulan ini',
                    'label' => 'Jumlah Ibu hamil dapat tablet tambah darah (Fe) 30 tablet (Fe1) bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 6,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Ibu hamil dapat tablet tambah darah (Fe) 90 tablet (Fe2) bulan ini',
                    'label' => 'Jumlah Ibu hamil dapat tablet tambah darah (Fe) 90 tablet (Fe2) bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 7,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Balita diperiksa status anemia bulan ini',
                    'label' => 'Jumlah Balita diperiksa status anemia bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 8,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Balita yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'label' => 'Jumlah Balita yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 9,
                    // 'category_id' => 19,
                    'name' => 'Jumlah WUS (15 - 45 th) diperiksa status anemia bulan ini',
                    'label' => 'Jumlah WUS (15 - 45 th) diperiksa status anemia bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 10,
                    // 'category_id' => 19,
                    'name' => 'Jumlah WUS (15 - 45 th) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'label' => 'Jumlah WUS (15 - 45 th) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 11,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Remaja Putri (14 - 18 th) diperiksa status anemia bulan ini',
                    'label' => 'Jumlah Remaja Putri (14 - 18 th) diperiksa status anemia bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 12,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Remaja Putri (14 - 18 th) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'label' => 'Jumlah Remaja Putri (14 - 18 th) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 13,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Tenaga Kerja Wanita (nakerwan) diperiksa status anemia bulan ini',
                    'label' => ' Jumlah Tenaga Kerja Wanita (nakerwan) diperiksa status anemia bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 14,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Tenaga Kerja Wanita (nakerwan) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'label' => 'Jumlah Tenaga Kerja Wanita (nakerwan) yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 15,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Ibu hamil diperiksa status anemia bulan ini',
                    'label' => 'Jumlah Ibu hamil diperiksa status anemia bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 16,
                    // 'category_id' => 19,
                    'name' => 'Jumlah Ibu hamil yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'label' => 'Jumlah Ibu hamil yang diperiksa dengan status anemia < 11 gr % bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 17,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita yang ada bulan ini',
                    'label' => 'Jumlah Balita yang ada bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 18,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita yang mempunyai KMS bulan ini',
                    'label' => 'Jumlah Balita yang mempunyai KMS bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 19,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita yang Naik berat badannya bulan ini',
                    'label' => 'Jumlah Balita yang Naik berat badannya bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 20,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita yang Tidak naik/tetap berat badannya bulan ini',
                    'label' => 'Jumlah Balita yang Tidak naik/tetap berat badannya bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 21,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita yang ditimbang bulan ini tetapi tidak ditimbang bulan lalu',
                    'label' => 'Jumlah Balita yang ditimbang bulan ini tetapi tidak ditimbang bulan lalu',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 22,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita yang Baru ditimbang bulan ini',
                    'label' => 'Jumlah Balita yang Baru ditimbang bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 23,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita yang dapat ditimbang bulan ini',
                    'label' => 'Jumlah Balita yang dapat ditimbang bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 24,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita yang tidak dapat ditimbang bulan ini',
                    'label' => 'Jumlah Balita yang tidak dapat ditimbang bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 25,
                    // 'category_id' => 20,
                    'name' => 'jumlah Balita dengan Berat badan di Bawah Garis Merah (BGM) bulan ini',
                    'label' => 'jumlah Balita dengan Berat badan di Bawah Garis Merah (BGM) bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 26,
                    // 'category_id' => 20,
                    'name' => 'Jumlah Balita gizi buruk bulan ini',
                    'label' => 'Jumlah Balita gizi buruk bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 27,
                    // 'category_id' => 21,
                    'name' => 'Jumlah penderita GAKY laki-laki bulan ini',
                    'label' => 'Jumlah penderita GAKY laki-laki bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 28,
                    // 'category_id' => 21,
                    'name' => 'Jumlah penderita GAKY perempuan bulan ini',
                    'label' => 'Jumlah penderita GAKY perempuan bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 29,
                    // 'category_id' => 21,
                    'name' => 'Jumlah ibu hamil mendapat kapsul yodium',
                    'label' => 'Jumlah ibu hamil mendapat kapsul yodium',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 30,
                    // 'category_id' => 21,
                    'name' => 'Jumlah penduduk lainnya mendapat kapsul yodium',
                    'label' => 'Jumlah penduduk lainnya mendapat kapsul yodium',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 31,
                    // 'category_id' => 22,
                    'name' => 'Jumlah Ibu hamil baru, diukur LILA (Lingkar Lengan Atas) bulan ini',
                    'label' => 'Jumlah Ibu hamil baru, diukur LILA (Lingkar Lengan Atas) bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 32,
                    // 'category_id' => 22,
                    'name' => 'Jumlah Ibu hamil baru, dengan LILA < 23,5 cm bulan ini',
                    'label' => 'Jumlah Ibu hamil baru, dengan LILA < 23,5 cm bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 33,
                    // 'category_id' => 22,
                    'name' => 'Jumlah WUS baru, yang diukur LILA (Lingkar Lengan Atas) bulan ini',
                    'label' => 'Jumlah WUS baru, yang diukur LILA (Lingkar Lengan Atas) bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 34,
                    // 'category_id' => 22,
                    'name' => 'Jumlah WUS baru, dengan LILA < 23,5 cm bulan ini',
                    'label' => 'Jumlah WUS baru, dengan LILA < 23,5 cm bulan ini',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 35,
                    // 'category_id' => 23,
                    'name' => 'Jumlah kunjungan K1 Bumil',
                    'label' => 'Jumlah kunjungan K1 Bumil',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 36,
                    // 'category_id' => 23,
                    'name' => 'Jumlah kunjungan Bumil lama',
                    'label' => 'Jumlah kunjungan Bumil lama',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 37,
                    // 'category_id' => 23,
                    'name' => 'K2',
                    'label' => 'K2',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 38,
                    // 'category_id' => 23 ,
                    'name' => 'K3',
                    'label' => 'K3',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 39,
                    // 'category_id' => 23,
                    'name' => 'K4',
                    'label' => 'K4',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 40,
                    // 'category_id' => 23,
                    'name' => 'Kunjungan Bumil dengan faktor risiko: < 20 th',
                    'label' => 'Kunjungan Bumil dengan faktor risiko: < 20 th',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 41,
                    // 'category_id' => 23,
                    'name' => 'Kunjungan Bumil dengan faktor risiko: > 35 th',
                    'label' => 'Kunjungan Bumil dengan faktor risiko: > 35 th',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ], [
                    // 'id' => 42,
                    // 'category_id' => 23,
                    'name' => 'Kunjungan Bumil dengan faktor risiko: Spacing < 2 th',
                    'label' => 'Kunjungan Bumil dengan faktor risiko: Spacing < 2 th',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 43,
                    // 'category_id' => 23,
                    'name' => 'Kunjungan Bumil dengan faktor risiko: Paritas > 5 th',
                    'label' => 'Kunjungan Bumil dengan faktor risiko: Paritas > 5 th',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 44,
                    // 'category_id' => 23,
                    'name' => 'Kunjungan Bumil dengan faktor risiko: HB 11 gram %',
                    'label' => 'Kunjungan Bumil dengan faktor risiko: HB 11 gram %',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' =>45 ,
                    // 'category_id' => 23,
                    'name' => 'Kunjungan Bumil dengan faktor risiko: BB Kg Triwulan III < 45 Kg',
                    'label' => 'Kunjungan Bumil dengan faktor risiko: BB Kg Triwulan III < 45 Kg',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 46,
                    // 'category_id' => 23,
                    'name' => 'Kunjungan Bumil dengan faktor risiko: TB < 145 cm',
                    'label' => 'Kunjungan Bumil dengan faktor risiko: TB < 145 cm',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 47,
                    // 'category_id' => 23,
                    'name' => 'Imunisasi TT Bumil (TT1, TT2): TT1',
                    'label' => 'Imunisasi TT Bumil (TT1, TT2): TT1',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 48,
                    // 'category_id' => 23,
                    'name' => 'Imunisasi TT Bumil (TT1, TT2): TT2',
                    'label' => 'Imunisasi TT Bumil (TT1, TT2): TT2',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 49,
                    // 'category_id' => 23,
                    'name' => 'Pemberian tablet Fe Bumil: Fe1',
                    'label' => 'Pemberian tablet Fe Bumil: Fe1',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 50,
                    // 'category_id' => 23,
                    'name' => 'Pemberian tablet Fe Bumil: Fe2',
                    'label' => 'Pemberian tablet Fe Bumil: Fe2',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 51,
                    // 'category_id' => 23,
                    'name' => 'Pemberian tablet Fe Bumil: Fe3',
                    'label' => 'Pemberian tablet Fe Bumil: Fe3',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 52,
                    // 'category_id' => 23,
                    'name' => 'Jumlah kesakitan dan kematian Bumil yang ditangani: Pendarahan',
                    'label' => 'Jumlah kesakitan dan kematian Bumil yang ditangani: Pendarahan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 53,
                    // 'category_id' => 23,
                    'name' => 'Jumlah kesakitan dan kematian Bumil yang ditangani: Infeksi jalan lahir',
                    'label' => 'Jumlah kesakitan dan kematian Bumil yang ditangani: Infeksi jalan lahir',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 54,
                    // 'category_id' => 23,
                    'name' => 'Jumlah kesakitan dan kematian Bumil yang ditangani: Preeklamasi/Eklamsi',
                    'label' => 'Jumlah kesakitan dan kematian Bumil yang ditangani: Preeklamasi/Eklamsi',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 55,
                    // 'category_id' => 23,
                    'name' => 'Jumlah kesakitan dan kematian Bumil yang ditangani: Sebab lain',
                    'label' => 'Jumlah kesakitan dan kematian Bumil yang ditangani: Sebab lain',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 56,
                    // 'category_id' => 23,
                    'name' => 'Deteksi resti bumil oleh nakes',
                    'label' => 'Deteksi resti bumil oleh nakes',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 57,
                    // 'category_id' => 23,
                    'name' => 'Deteksi resti bumil oleh masyarakat',
                    'label' => 'Deteksi resti bumil oleh masyarakat',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 58,
                    // 'category_id' => 24,
                    'name' => 'Persalinan: < 20 tahun',
                    'label' => 'Persalinan: < 20 tahun',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 59,
                    // 'category_id' => 24,
                    'name' => 'Persalinan: 20 - 24 tahun',
                    'label' => 'Persalinan: 20 - 24 tahun',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 60,
                    // 'category_id' => 24,
                    'name' => 'Persalinan: 25 - 29 tahun',
                    'label' => 'Persalinan: 25 - 29 tahun',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 61,
                    // 'category_id' => 24,
                    'name' => 'Persalinan: 30 - 34 tahun',
                    'label' => 'Persalinan: 30 - 34 tahun',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 62,
                    // 'category_id' => 24,
                    'name' => 'Persalinan: > 35 tahun',
                    'label' => 'Persalinan: > 35 tahun',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 63,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan ditolong oleh Nakes: Lahir hidup',
                    'label' => 'Jumlah persalinan ditolong oleh Nakes: Lahir hidup',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 64,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan ditolong oleh Nakes: Lahir mati',
                    'label' => 'Jumlah persalinan ditolong oleh Nakes: Lahir mati',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 65 ,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan ditolong oleh Nakes: BBLR (BB < 2500 gram)',
                    'label' => 'Jumlah persalinan ditolong oleh Nakes: BBLR (BB < 2500 gram)',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 66,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan dukun didampingi oleh Nakes : Lahir hidup',
                    'label' => 'Jumlah persalinan dukun didampingi oleh Nakes : Lahir hidup',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 67,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan dukun didampingi oleh Nakes : Lahir mati',
                    'label' => 'Jumlah persalinan dukun didampingi oleh Nakes : Lahir mati',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 68,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan dukun didampingi oleh Nakes : BBLR (BB < 2500 gram)',
                    'label' => 'Jumlah persalinan dukun didampingi oleh Nakes : BBLR (BB < 2500 gram)',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 69,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan ditolong oleh dukun terlatih/tidak telatih : Lahir hidup',
                    'label' => 'Jumlah persalinan ditolong oleh dukun terlatih/tidak telatih : Lahir hidup',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 70,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan ditolong oleh dukun terlatih/tidak telatih : Lahir mati',
                    'label' => 'Jumlah persalinan ditolong oleh dukun terlatih/tidak telatih : Lahir mati',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 71,
                    // 'category_id' => 24,
                    'name' => 'Jumlah persalinan ditolong oleh dukun terlatih/tidak telatih : BBLR (BB < 2500 gram)',
                    'label' => 'Jumlah persalinan ditolong oleh dukun terlatih/tidak telatih : BBLR (BB < 2500 gram)',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 72,
                    // 'category_id' => 24,
                    'name' => 'Kunjungan Neonatus: 0 - 7 hari',
                    'label' => 'Kunjungan Neonatus: 0 - 7 hari',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 73,
                    // 'category_id' => 24,
                    'name' => 'Kunjungan Neonatus: 7 - 28 hari',
                    'label' => 'Kunjungan Neonatus: 7 - 28 hari',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 74,
                    // 'category_id' => 24,
                    'name' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani: Pendarahan',
                    'label' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani: Pendarahan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 75,
                    // 'category_id' => 24,
                    'name' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani: Infeksi jalan lahir',
                    'label' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani: Infeksi jalan lahir',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 76,
                    // 'category_id' => 24,
                    'name' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani: Preeklamasi/Eklamsi',
                    'label' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani: Preeklamasi/Eklamsi',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 77,
                    // 'category_id' => 24,
                    'name' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani: Sebab lain',
                    'label' => 'Jumlah kesakitan dan kematian ibu bersalin ditangani: Sebab lain',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 78,
                    // 'category_id' => 24,
                    'name' => 'Jumlah kesakitan dan kematian ibu nifas ditangani: Pendarahan',
                    'label' => 'Jumlah kesakitan dan kematian ibu nifas ditangani: Pendarahan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 79,
                    // 'category_id' => 24,
                    'name' => 'Jumlah kesakitan dan kematian ibu nifas ditangani: Infeksi jalan lahir',
                    'label' => 'Jumlah kesakitan dan kematian ibu nifas ditangani: Infeksi jalan lahir',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 80,
                    // 'category_id' => 24,
                    'name' => 'Jumlah kesakitan dan kematian ibu nifas ditangani: Preeklamasi/Eklamsi',
                    'label' => 'Jumlah kesakitan dan kematian ibu nifas ditangani: Preeklamasi/Eklamsi',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 81,
                    // 'category_id' => 24,
                    'name' => 'Jumlah kesakitan dan kematian ibu nifas ditangani: Sebab lain',
                    'label' => 'Jumlah kesakitan dan kematian ibu nifas ditangani: Sebab lain',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 82,
                    // 'category_id' => 25 ,
                    'name' => 'Kunjungan baru',
                    'label' => 'Kunjungan baru',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 83,
                    // 'category_id' => 25,
                    'name' => 'Kunjungan lama',
                    'label' => 'Kunjungan lama',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 84,
                    // 'category_id' => 25,
                    'name' => 'Akseptor baru Buteki',
                    'label' => 'Akseptor baru Buteki',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 85,
                    // 'category_id' => 25,
                    'name' => 'Akseptor aktif Buteki',
                    'label' => 'Akseptor aktif Buteki',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 86,
                    // 'category_id' => 25,
                    'name' => 'Akseptor aktif seluruh (CU)',
                    'label' => 'Akseptor aktif seluruh (CU)',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 87,
                    // 'category_id' => 25,
                    'name' => 'Buteki dapat Fe',
                    'label' => 'Buteki dapat Fe',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 88,
                    // 'category_id' => 25 ,
                    'name' => 'Buteki dapat Vitamin A dosis tinggi',
                    'label' => 'Buteki dapat Vitamin A dosis tinggi',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 89,
                    // 'category_id' => 25,
                    'name' => 'ASI Eksklusif 0 - 6 bulan',
                    'label' => 'ASI Eksklusif 0 - 6 bulan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 90,
                    // 'category_id' => 26,
                    'name' => 'Kunjungan baru diperiksa',
                    'label' => 'Kunjungan baru diperiksa',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 91,
                    // 'category_id' => 26,
                    'name' => 'Kunjungan baru dirujuk',
                    'label' => 'Kunjungan baru dirujuk',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 92,
                    // 'category_id' => 26,
                    'name' => 'Kunjungan lama diperiksa',
                    'label' => 'Kunjungan lama diperiksa',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 93,
                    // 'category_id' => 26,
                    'name' => 'Kunjungan lama dirujuk',
                    'label' => 'Kunjungan lama dirujuk',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 94,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): BBLR',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): BBLR',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 95,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): Tetanus Neonatorium',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): Tetanus Neonatorium',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 96,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): BBLR dirujuk ke RSU',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): BBLR dirujuk ke RSU',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 97,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): Tetanus Neonatorium dirujuk ke RSU',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): Tetanus Neonatorium dirujuk ke RSU',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 98,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): Oleh sebab lain',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (0 - 7 hari): Oleh sebab lain',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 99,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari):  BBLR',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari):  BBLR',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 100,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari): Tetanus Neonatorium',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari): Tetanus Neonatorium ',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 101,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari): BBLR dirujuk ke RSU',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari): BBLR dirujuk ke RSU',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 102,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari): Tetanus Neonatorium dirujuk ke RSU',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari): Tetanus Neonatorium dirujuk ke RSU',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 103,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari): Oleh sebab lain',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (8 - 28 hari): Oleh sebab lain',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 104,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): BBLR',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): BBLR',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 105,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): Tetanus Neonatorium',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): Tetanus Neonatorium',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 106,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): BBLR dirujuk ke RSU',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): BBLR dirujuk ke RSU',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 107,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): Tetanus Neonatorium dirujuk ke RSU',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): Tetanus Neonatorium dirujuk ke RSU',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 108,
                    // 'category_id' => 26,
                    'name' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): Oleh sebab lain',
                    'label' => 'Jumlah kesakitan dan kematian Perinatal (28 hari - 1 tahun): Oleh sebab lain',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 109,
                    // 'category_id' => 27,
                    'name' => 'Kunjungan baru diperiksa',
                    'label' => 'Kunjungan baru diperiksa',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 110,
                    // 'category_id' => 27,
                    'name' => 'Kunjungan baru drujuk',
                    'label' => 'Kunjungan baru drujuk',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 111,
                    // 'category_id' => 27,
                    'name' => 'Kunjungan lama diperiksa',
                    'label' => 'Kunjungan lama diperiksa',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 112,
                    // 'category_id' => 27,
                    'name' => 'Kunjungan lama dirujuk',
                    'label' => 'Kunjungan lama dirujuk',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 113,
                    // 'category_id' => 27,
                    'name' => 'Jumlah kesakitan dan kematian anak balita',
                    'label' => 'Jumlah kesakitan dan kematian anak balita',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 114,
                    // 'category_id' => 28,
                    'name' => 'Jumlah bayi divaksinasi campak',
                    'label' => 'Jumlah bayi divaksinasi campak',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 115,
                    // 'category_id' => 28,
                    'name' => 'Jumlah bayi divaksinasi DPT I',
                    'label' => 'Jumlah bayi divaksinasi DPT I',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 116,
                    // 'category_id' => 28,
                    'name' => 'Jumlah bayi 0 - 7 hari divaksinasi hepatitis B',
                    'label' => 'Jumlah bayi 0 - 7 hari divaksinasi hepatitis B',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 117,
                    // 'category_id' => 28,
                    'name' => 'Jumlah bayi > 7 hari divaksinasi hepatitis B',
                    'label' => 'Jumlah bayi > 7 hari divaksinasi hepatitis B',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 118,
                    // 'category_id' => 28,
                    'name' => 'Jumlah Ibu Hamil divaksinasi TT I',
                    'label' => 'Jumlah Ibu Hamil divaksinasi TT I',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 119,
                    // 'category_id' => 28,
                    'name' => 'Jumlah Ibu Hamil divaksinasi TT II',
                    'label' => 'Jumlah Ibu Hamil divaksinasi TT II',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 120,
                    // 'category_id' => 28,
                    'name' => 'Jumlah Ibu Hamil divaksinasi TT Boster',
                    'label' => 'Jumlah Ibu Hamil divaksinasi TT Boster',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 121,
                    // 'category_id' => 28,
                    'name' => 'Jumlah wanita usia subur/calon pengantin (WUS), divaksinasi TT I',
                    'label' => 'Jumlah wanita usia subur/calon pengantin (WUS), divaksinasi TT I',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 122,
                    // 'category_id' => 28,
                    'name' => 'Jumlah murid SD kelas I divaksinasi DP',
                    'label' => 'Jumlah murid SD kelas I divaksinasi DP',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 123,
                    // 'category_id' => 28,
                    'name' => 'Jumlah murid SD kelas II dan III divaksinasi TT',
                    'label' => 'Jumlah murid SD kelas II dan III divaksinasi TT',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 124,
                    // 'category_id' => 28,
                    'name' => 'Jumlah bayi divaksinasi BCG',
                    'label' => 'Jumlah bayi divaksinasi BCG',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 125,
                    // 'category_id' => 29,
                    'name' => 'Jumlah kasus AFP baru (0 - 15 tahun) ditemukan',
                    'label' => 'Jumlah kasus AFP baru (0 - 15 tahun) ditemukan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[ // TODO: Missing id, after this id + 1
                    // 'id' => 125,
                    // 'category_id' => 29,
                    'name' => 'Jumlah kasus tetanus neonatorum ditemukan',
                    'label' => 'Jumlah kasus tetanus neonatorum ditemukan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 126,
                    // 'category_id' => 30,
                    'name' => 'Jumlah kasus tetanus neonatorum ditemukan',
                    'label' => 'Jumlah kasus tetanus neonatorum ditemukan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 127,
                    // 'category_id' => 30,
                    'name' => 'Jumlah kasus tetanus neonatorum dilacak',
                    'label' => 'Jumlah kasus tetanus neonatorum dilacak',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 128,
                    // 'category_id' => 31,
                    'name' => 'Jumlah penderita malaria berat dan komplikasi',
                    'label' => 'Jumlah penderita malaria berat dan komplikasi',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 129,
                    // 'category_id' => 31,
                    'name' => 'Jumlah Bumil yang memperoleh pengobatan profilaksis/pencegahan',
                    'label' => 'Jumlah Bumil yang memperoleh pengobatan profilaksis/pencegahan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' =>130 ,
                    // 'category_id' => 31,
                    'name' => 'Jumlah rumah yang disemprot',
                    'label' => 'Jumlah rumah yang disemprot',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 131,
                    // 'category_id' => 31,
                    'name' => 'Jumlah penderita malaria klinis',
                    'label' => 'Jumlah penderita malaria klinis',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 132,
                    // 'category_id' => 31,
                    'name' => 'Jumlah penderita pemeriksaan lab',
                    'label' => 'Jumlah penderita pemeriksaan lab',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 133,
                    // 'category_id' => 32,
                    'name' => 'Jumlah pelacakan penderita DBD',
                    'label' => 'Jumlah pelacakan penderita DBD',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 134,
                    // 'category_id' => 32,
                    'name' => 'Jumlah fogging fokus',
                    'label' => 'Jumlah fogging fokus',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 135,
                    // 'category_id' => 32,
                    'name' => 'Jumlah desa/kelurahan diabatisasi selektif',
                    'label' => 'Jumlah desa/kelurahan diabatisasi selektif',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 136,
                    // 'category_id' => 32,
                    'name' => 'Jumlah desa/kelurahan dilakukan Pemberantasan Sarang Nyamuk',
                    'label' => 'Jumlah desa/kelurahan dilakukan Pemberantasan Sarang Nyamuk',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 137,
                    // 'category_id' => 32,
                    'name' => 'Jumlah rumah yang dilakukan pemeriksaan jentik',
                    'label' => 'Jumlah rumah yang dilakukan pemeriksaan jentik',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 138,
                    // 'category_id' => 32,
                    'name' => 'Jumlah rumah yang ada jentik',
                    'label' => 'Jumlah rumah yang ada jentik',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],[
                    // 'id' => 139,
                    // 'category_id' => 33,
                    'name' => 'Jumlah penderita digigit oleh hewan penular rabies',
                    'label' => 'Jumlah penderita digigit oleh hewan penular rabies',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 140,
                    // 'category_id' => 33,
                    'name' => 'Jumlah penderita gigitan yg di Vaksin Anti Rabies (VAR) atau VAR (+) Serum Anti Rabies (SAR)',
                    'label' => 'Jumlah penderita gigitan yg di Vaksin Anti Rabies (VAR) atau VAR (+) Serum Anti Rabies (SAR)',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 141,
                    // 'category_id' => 34,
                    'name' => 'Jumlah desa endemis',
                    'label' => 'Jumlah desa endemis',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 142,
                    // 'category_id' => 34 ,
                    'name' => 'Jumlah desa dengan cakupan pengobatan massal > 80 %',
                    'label' => 'Jumlah desa dengan cakupan pengobatan massal > 80 %',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 143,
                    // 'category_id' => 35,
                    'name' => 'Jumlah yang diobati',
                    'label' => 'Jumlah yang diobati',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 144,
                    // 'category_id' => 36,
                    'name' => 'Jumlah penduduk 0 - 14 tahun yang diperiksa untuk Frambusia',
                    'label' => 'Jumlah penduduk 0 - 14 tahun yang diperiksa untuk Frambusia',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 145,
                    // 'category_id' => 36,
                    'name' => 'Jumlah penderita Frambusia yang ditemukan',
                    'label' => 'Jumlah penderita Frambusia yang ditemukan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 146,
                    // 'category_id' => 36,
                    'name' => 'Jumlah penderita/kontak penderita yang diobati',
                    'label' => 'Jumlah penderita/kontak penderita yang diobati',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 147,
                    // 'category_id' => 37,
                    'name' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat oralit',
                    'label' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat oralit',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 148,
                    // 'category_id' => 37,
                    'name' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat infus',
                    'label' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat infus',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 149,
                    // 'category_id' => 37,
                    'name' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat antibiotik',
                    'label' => 'Jumlah penderita diare (termasuk tersangka kolera & disentri) dapat antibiotik',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 150,
                    // 'category_id' => 38,
                    'name' => 'Jumlah penderita Pneumonia',
                    'label' => 'Jumlah penderita Pneumonia',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 151,
                    // 'category_id' => 38,
                    'name' => 'Jumlah penderita Pneumonia balita dirujuk dokter',
                    'label' => 'Jumlah penderita Pneumonia balita dirujuk dokter',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 152,
                    // 'category_id' => 39,
                    'name' => 'Jumlah penderita BTA positif baru diobati',
                    'label' => 'Jumlah penderita BTA positif baru diobati',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 153,
                    // 'category_id' => 39,
                    'name' => 'Jumlah penderita BTA negatif dan dengan Ronsen (+) diobati',
                    'label' => 'Jumlah penderita BTA negatif dan dengan Ronsen (+) diobati',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 154,
                    // 'category_id' => 39,
                    'name' => 'Jumlah penderita mengikuti pengobatan lengkap',
                    'label' => 'Jumlah penderita mengikuti pengobatan lengkap',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 155,
                    // 'category_id' => 39,
                    'name' => 'Jumlah penderita TB Paru yang sembuh',
                    'label' => 'Jumlah penderita TB Paru yang sembuh',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 156,
                    // 'category_id' => 39,
                    'name' => 'Jumlah penderita kambuh',
                    'label' => 'Jumlah penderita kambuh',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 157,
                    // 'category_id' => 40,
                    'name' => 'Jumlah penderita terdaftar (PB/Pausibasiler + MB/Multibasiler)',
                    'label' => 'Jumlah penderita terdaftar (PB/Pausibasiler + MB/Multibasiler)',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 158,
                    // 'category_id' => 40,
                    'name' => 'Jumlah penderita baru yang ditemukan',
                    'label' => 'Jumlah penderita baru yang ditemukan',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 159,
                    // 'category_id' => 40,
                    'name' => 'Jumlah penderita MB di antara kasus baru',
                    'label' => 'Jumlah penderita MB di antara kasus baru',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 160,
                    // 'category_id' => 40,
                    'name' => 'Jumlah penderita baru menurut cacat tingkat II',
                    'label' => 'Jumlah penderita baru menurut cacat tingkat II',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 161,
                    // 'category_id' => 40,
                    'name' => 'Jumlah penderita MB yang mendapat pengobatan MDT',
                    'label' => 'Jumlah penderita MB yang mendapat pengobatan MDT',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 162,
                    // 'category_id' => 40,
                    'name' => 'Jumlah penderita PB yang mendapat pengobatan MDT',
                    'label' => 'Jumlah penderita PB yang mendapat pengobatan MDT',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 163,
                    // 'category_id' => 40,
                    'name' => 'Jumlah penderita MB yang mendapat pengobatan MDT komplit (RFT)',
                    'label' => 'Jumlah penderita MB yang mendapat pengobatan MDT komplit (RFT)',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
                [
                    // 'id' => 164,
                    // 'category_id' => 40,
                    'name' => 'Jumlah penderita PB yang mendapat pengobatan MDT komplit (RFT)',
                    'label' => 'Jumlah penderita PB yang mendapat pengobatan MDT komplit (RFT)',
                    'unit_label' => ' ',
                    'created_at' => date("Y-m-d H:i:s"),
                    'updated_at' => date("Y-m-d H:i:s"),
                ],
            ]
        );
    }
}
