
<?php

use Illuminate\Database\Seeder;

class LB4ProductionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $parent = [
            [ // main parent
                'id' => 3600,
                'name' => 'kunjungan_puskesmas',
                'label' => 'Kunjungan Puskesmas',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3601,
                'name' => 'rawat_tinggal',
                'label' => 'Rawat Tinggal',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3602,
                'name' => 'kegiatan_perawatan_kesehatan_masyarakat',
                'label' => 'Kegiatan Perawatan Kesehatan Masyarakat',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3603,
                'name' => 'frekuensi_kegiatan_puskesmas_diluar_gedung',
                'label' => 'Frekuensi Kegiatan Puskesmas diluar Gedung',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3604,
                'name' => 'penduduk_yang_menggunakan_sarana_kesehatan_swasta',
                'label' => 'Penduduk Yang Menggunakan Sarana Kesehatan Swasta',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3605,
                'name' => 'pelayanan_medik_dasar_kesehatan_gigi',
                'label' => 'Pelayanan Medik Dasar Kesehatan Gigi',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3606,
                'name' => 'kegiatan_pelayanan_jpkm',
                'label' => 'Kegiatan Pelayanan JPKM',
                'is_parent' => true,
                'indicator_parent_id' => null,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3607,
                'name' => 'kegiatan_sekolah',
                'label' => 'Kegiatan Sekolah',
                ' is_parent ' => true,
                ' indicator_parent_id ' => null,
                ' unit_label ' => ' orang ',
                ' created_at ' => date("Y-m-d H:i:s"),
                ' updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3608,
                'name' => 'kesehatan_olahraga',
                'label' => 'Kesehatan Olah Raga',
                ' is_parent ' => true,
                ' indicator_parent_id ' => null,
                ' unit_label ' => ' orang ',
                ' created_at ' => date("Y-m-d H:i:s"),
                ' updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3609,
                'name' => 'kegiatan_penyuluhan_kesehatan_masyarakat',
                'label' => 'Kegiatan Penyuluhan Kesehatan Masyarakat',
                ' is_parent ' => true,
                ' indicator_parent_id ' => null,
                ' unit_label ' => ' orang ',
                ' created_at ' => date("Y-m-d H:i:s"),
                ' updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3610,
                'name' => 'kegiatan_ukbm',
                'label' => 'Kegiatan UKBM',
                ' is_parent ' => true,
                ' indicator_parent_id ' => null,
                ' unit_label ' => ' orang ',
                ' created_at ' => date("Y-m-d H:i:s"),
                ' updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3611,
                'name' => 'kesehatan_lingkungan',
                'label' => 'Kesehatan Lingkungan',
                ' is_parent ' => true,
                ' indicator_parent_id ' => null,
                ' unit_label ' => ' orang ',
                ' created_at ' => date("Y-m-d H:i:s"),
                ' updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3612,
                'name' => 'laboratorium',
                'label' => 'Laboratorium',
                ' is_parent ' => true,
                ' indicator_parent_id ' => null,
                ' unit_label ' => ' orang ',
                ' created_at ' => date("Y-m-d H:i:s"),
                ' updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // main parent
                'id' => 3613,
                'name' => 'jaminan_mutu',
                'label' => 'Jaminan Mutu / Quality Assurance',
                ' is_parent ' => true,
                ' indicator_parent_id ' => null,
                ' unit_label ' => ' orang ',
                ' created_at ' => date("Y-m-d H:i:s"),
                ' updated_at' => date("Y-m-d H:i:s"),
            ],
            /**
             * Child
             */
            [ // 3600 Child
                'id' => 3614,
                'name' => 'kp_jumlah_kunjungan_puskesmas',
                'label' => 'Jumlah Kunjungan Puskesmas',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3600 Child
                'id' => 3615,
                'name' => 'kp_jumlah_kunjungan_dengan_kartu_sehat',
                'label' => 'Jumlah Kunjungan dengan Kartu Sehat',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3600 Child
                'id' => 3616,
                'name' => 'kp_jumlah_kunjungan_rawat_jalan',
                'label' => 'Jumlah Kunjungan Rawat Jalan',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3616 Child
                'id' => 3617,
                'name' => 'jk_rawat_jalan_baru',
                'label' => 'Jumlah Kunjungan Rawat Jalan Baru',
                'is_parent' => false,
                'indicator_parent_id' => 3616,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3616 Child
                'id' => 3618,
                'name' => 'jk_rawat_jalan_lama',
                'label' => 'Jumlah Kunjungan Rawat Jalan Lama',
                'is_parent' => false,
                'indicator_parent_id' => 3616,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3600 Child
                'id' => 3619,
                'name' => 'kp_jumlah_kunjungan_rawat_jalan_umur_60',
                'label' => 'Jumlah Kunjungan Rawat Jalan Umur  >= 60',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3600 Child
                'id' => 3620,
                'name' => 'kp_jumlah_kunjungan_rawat_jalan_gigi',
                'label' => 'Jumlah Kunjungan Rawat Jalan Gigi',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3600 Child
                'id' => 3621,
                'name' => 'kp_jumlah_kunjungan_polindes',
                'label' => 'Jumlah Kunjungan Polindes',
                'is_parent' => false,
                'indicator_parent_id' => 3600,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3601 Child
                'id' => 3622,
                'name' => 'rt_jumlah_penderita_yang_dirawat',
                'label' => 'Jumlah Penderita Yang Dirawat',
                'is_parent' => false,
                'indicator_parent_id' => 3601,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3601 Child
                'id' => 3623,
                'name' => 'rt_jumlah_penderita yang_keluar',
                'label' => 'Jumlah Penderita Yang Keluar',
                'is_parent' => false,
                'indicator_parent_id' => 3601,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3601 Child
                'id' => 3624,
                'name' => 'rt_jumlah_hari_perawatan',
                'label' => 'Jumlah hari Perawatan',
                'is_parent' => false,
                'indicator_parent_id' => 3601,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3601 Child
                'id' => 3625,
                'name' => 'rt_jumlah_ibu_hamil_melahirkan_nifas_dengan_kelainan_yang_dirawat',
                'label' => 'Jumlah Ibu Hamil Melahirkan, Nifas dengan Kelainan yang Dirawat',
                'is_parent' => false,
                'indicator_parent_id' => 3601,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3601 Child
                'id' => 3626,
                'name' => 'rt_jumlah_balita_sakit_dengan_kelianan_yang_dirawat',
                'label' => 'Jumlah balita (Sakit, dengan kelainan) yang Dirawat',
                'is_parent' => false,
                'indicator_parent_id' => 3601,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3601 Child
                'id' => 3627,
                'name' => 'rt_jumlah_kasus_cidera_kecelakaan_yang_dirawat',
                'label' => 'Jumlah Kasus Cidera/ Kecelakaan yang Dirawat',
                'is_parent' => false,
                'indicator_parent_id' => 3601,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3601 Child
                'id' => 3628,
                'name' => 'rt_jumlah_penderita_dengan_kasus_lainnya',
                'label' => 'Jumlah Penderita dengan Kasus Lainnya',
                'is_parent' => false,
                'indicator_parent_id' => 3601,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3629,
                'name' => 'kpkm_jumlah_keluarga_dengan_penderita_tb_baru_yang_dibina',
                'label' => 'Jumlah Keluarga dengan Penderita TB Baru yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3630,
                'name' => 'kpkm_jumlah_keluarga_dengan_penderita_tb_kusta_yang_dibina',
                'label' => 'Jumlah Keluarga dengan Penderita TB Kusta yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3631,
                'name' => 'kpkm_jumlah_keluarga_dengan_ibu_hamil_melahirkan_nifas_risti_yang_dibina',
                'label' => 'Jumlah Keluarga dengan Ibu Hamil Melahirkan, Nifas Risti yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3632,
                'name' => 'kpkm_jumlah_keluarga_dengan_bayi_risti_pneumpnia_berat_bblr_yang_dibina',
                'label' => 'Jumlah Keluarga dengan Bayi Risti (Pneumonia Berat, BBLR) yang Dibina ',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3632,
                'name' => 'kpkm_jumlah_keluarga_dengan_bayi_risti_pneumpnia_berat_bblr_yang_dibina',
                'label' => 'Jumlah Keluarga dengan Bayi Risti (Pneumonia Berat, BBLR) yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3633,
                'name' => 'kpkm_jumlah_keluarga_dengan_tetanus_neonatorum',
                'label' => 'Jumlah Keluarga dengan Tetanus Neonatorum',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3634,
                'name' => 'kpkm_jumlah_keluarga_dengan_anak_balita_risti_yang_dibina',
                'label' => 'Jumlah Keluarga dengan Anak Balita Risti yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3635,
                'name' => 'kpkm_jumlah_keluarga_dengan_usia_balita_risti_yang_dibina',
                'label' => 'Jumlah Keluarga dengan Usia Balita Risti yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3636,
                'name' => 'kpkm_jumlah_keluarga_dengan_resiko_lainnya_yang_dibina',
                'label' => 'Jumlah Keluarga dengan Resiko Lainnya yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3637,
                'name' => 'kpkm_jumlah_keluarga_yang_mempunyai_kartu_sehat_yang_dibina',
                'label' => 'Jumlah Keluarga yang Mempunyai Kartu Sehat yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3602 Child
                'id' => 3638,
                'name' => 'kpkm_jumlah_panti_kelompok_khusus_yang_dibina',
                'label' => 'Jumlah Panti/ Kelompok Khusus yang Dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3602,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3603 child
                'id' => 3639,
                'name' => 'fkp_diluar_gedung_jumlah_frekuensi_kegiatan_gizi_masyarakat',
                'label' => 'Jumlah Frekuensi Kegiatan Gizi Masyarakat',
                'is_parent' => false,
                'indicator_parent_id' => 3603,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3603 child
                'id' => 3640,
                'name' => 'fkp_diluar_gedung_jumlah_frekuensi_kegiatan_imunisasi',
                'label' => 'Jumlah Frekuensi Kegiatan Imunisasi',
                'is_parent' => false,
                'indicator_parent_id' => 3603,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3603 child
                'id' => 3641,
                'name' => 'fkp_diluar_gedung_jumlah_frekuensi_kegiatan_pemberantasan_penyakit',
                'label' => 'Jumlah Frekuensi Kegiatan Pemberantasan Penyakit',
                'is_parent' => false,
                'indicator_parent_id' => 3603,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3603 child
                'id' => 3642,
                'name' => 'fkp_diluar_gedung_jumlah_frekuensi_kegiatan_kesling',
                'label' => 'Jumlah Frekuensi Kegiatan Kesling',
                'is_parent' => false,
                'indicator_parent_id' => 3603,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3603 child
                'id' => 3643,
                'name' => 'fkp_diluar_gedung_jumlah_frekuensi_kegiatan_promosi_kesehatan',
                'label' => 'Jumlah Frekuensi Kegiatan Promosi Kesehatan',
                'is_parent' => false,
                'indicator_parent_id' => 3603,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3604 Child
                'id' => 3644,
                'name' => 'pmsks_jumlah_kunjungan_pada_praktek_dokter_perorangan',
                'label' => 'Jumlah Kunjungan pada Praktek Dokter Perorangan',
                'is_parent' => false,
                'indicator_parent_id' => 3604,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3604 Child
                'id' => 3645,
                'name' => 'pmsks_jumlah_kunjungan_pada_praktek_dokter__gigi_perorangan',
                'label' => 'Jumlah Kunjungan pada Praktek Dokter Gigi Perorangan',
                'is_parent' => false,
                'indicator_parent_id' => 3604,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3604 Child
                'id' => 3646,
                'name' => 'pmsks_jumlah_kunjungan_pada_praktek_dokter__kelompok',
                'label' => 'Jumlah Kunjungan pada Praktek Dokter Kelompok / Bersama',
                'is_parent' => false,
                'indicator_parent_id' => 3604,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3604 Child
                'id' => 3647,
                'name' => 'pmsks_jumlah_kunjungan_pada_praktek_bidan_rumah_bersalin',
                'label' => 'Jumlah Kunjungan pada Praktek Bidan / Rumah Bersalin',
                'is_parent' => false,
                'indicator_parent_id' => 3604,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3604 Child
                'id' => 3648,
                'name' => 'pmsks_jumlah_kunjungan_pada_balai_pengobatan_klinik_kesehatan',
                'label' => 'Jumlah Kunjungan pada Balai Pengobatan / Klinik Kesehatan',
                'is_parent' => false,
                'indicator_parent_id' => 3604,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3605 Child
                'id' => 3649,
                'name' => 'pmdk_gigi_jumlah_penambahan_gigi_tetap',
                'label' => 'Jumlah Penambahan Gigi Tetap',
                'is_parent' => false,
                'indicator_parent_id' => 3605,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3605 Child
                'id' => 3650,
                'name' => 'pmdk_gigi_jumlah_pencabutan_gigi_tetap',
                'label' => 'Jumlah Pencabutan Gigi Tetap',
                'is_parent' => false,
                'indicator_parent_id' => 3605,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3605 Child
                'id' => 3651,
                'name' => 'pmdk_gigi_jumlah_murid_sd_yang_perlu_perawatan_kesehatan_gigi',
                'label' => 'Jumlah Murid SD yang Perlu Perawatan Kesehatan Gigi',
                'is_parent' => false,
                'indicator_parent_id' => 3605,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3605 Child
                'id' => 3652,
                'name' => 'pmdk_gigi_jumlah_murid_sd_yang_mendapatkan_perawatan_kesehatan_gigi',
                'label' => 'Jumlah Murid SD yang Mendapatkan Perawatan Kesehatan Gigi',
                'is_parent' => false,
                'indicator_parent_id' => 3605,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3605 Child
                'id' => 3653,
                'name' => 'pmdk_gigi_jumlah_perawatan_gigi_lainnya',
                'label' => 'Jumlah Perawatan Gigi Lainnya',
                'is_parent' => false,
                'indicator_parent_id' => 3605,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3606 Child
                'id' => 3654,
                'name' => 'jpkm_jumlah_peserta_askes',
                'label' => 'Jumlah Peserta Askes',
                'is_parent' => false,
                'indicator_parent_id' => 3606,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3606 Child
                'id' => 3655,
                'name' => 'jpkm_jumlah_kunjungan_peserta_pt_askes',
                'label' => 'Jumlah Kunjungan Peserta PT. Askes',
                'is_parent' => false,
                'indicator_parent_id' => 3606,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3606 Child
                'id' => 3656,
                'name' => 'jpkm_jumlah_peserta_dana_sehat',
                'label' => 'Jumlah Peserta Dana Sehat',
                'is_parent' => false,
                'indicator_parent_id' => 3606,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3606 Child
                'id' => 3657,
                'name' => 'jpkm_jumlah_kunjungan_peserta_dana_sehat',
                'label' => 'Jumlah Kunjungan Peserta Dana Sehat',
                'is_parent' => false,
                'indicator_parent_id' => 3606,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3606 Child
                'id' => 3658,
                'name' => 'jpkm_jumlah_kunjungan_peserta_asuransi_kesehatan_lainnya',
                'label' => 'Jumlah Kunjungan Peserta Asuransi Kesehatan Lainnya',
                'is_parent' => false,
                'indicator_parent_id' => 3606,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3606 Child
                'id' => 3659,
                'name' => 'jpkm_jumlah_kunjungan_peserta_tabungan_sehat',
                'label' => 'Jumlah Peserta Tabungan Sehat',
                'is_parent' => false,
                'indicator_parent_id' => 3606,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3606 Child
                'id' => 3660,
                'name' => 'jpkm_jumlah_kunjungan_peserta_tabulin',
                'label' => 'Jumlah Peserta Tabulin',
                'is_parent' => false,
                'indicator_parent_id' => 3606,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3661,
                'name' => 'ks_jumlah_sekolah_dasar(SD)_dan_madrasah_ibtidaiyah(IM)_kelas_1_dengan_kegiatan_penjaringan_kesehatan',
                'label' => 'Jumlah Sekolah Dasar(SD) dan Madrasah Ibtidaiyah(IM) kelas 1 dengan Kegiatan Penjaringan Kesehatan',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3662,
                'name' => 'ks_jumlah_sekolah_dasar(SD)_dan_madrasah_ibtidaiyah(IM)_kelas_1_dengan_kegiatan_ukgs',
                'label' => 'Jumlah Sekolah Dasar(SD) dan Madrasah Ibtidaiyah(IM) kelas 1 dengan Kegiatan UKGS',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3663,
                'name' => 'ks_jumlah_sekolah_lanjut_tingkat_pertama(SLTP)_dan_madrasah_tsanawiyah(MTs)_kelas_1_dengan_penjaringan_kesehatan',
                'label' => 'Jumlah Sekolah Tingkat Pertama (SLTP) dan Madrasah Tsanawiyah(MTs) kelas 1 dengan Penjaringan Kesehatan',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3664,
                'name' => 'ks_jumlah_sekolah_lanjut_tingkat_atas(SLTA)_dan_madrasah_aliyah(MA)_kelas_1_dengan_penjaringan_kesehatan',
                'label' => 'Jumlah Sekolah Tingkat Atas (SLTA) dan Madrasah Aliyah(MA) kelas 1 dengan Penjaringan Kesehatan',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3665,
                'name' => 'ks_jumlah_sekolah_yang_diperiksa_sarana_kesehatan_lingkungan',
                'label' => 'Jumlah sekolah yang diperiksa sarana kesehatan lingkungan (sarana air bersih, pembuangan sampah, jamban dan air limbah)',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3666,
                'name' => 'ks_jumlah_sekolah_yang_memenuhi_syarat_kesehatan_lingkungan',
                'label' => 'Jumlah sekolah yang memenuhi syarat kesehatan lingkungan (sarana air bersih, pembuangan sampah, jamban dan air limbah)',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3667,
                'name' => 'ks_jumlah_kunjungan_pembinaan_uks_ke_sekolah',
                'label' => 'Jumlah kunjungan pembinaan UKS ke sekolah',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3668,
                'name' => 'ks_jumlah_sltp_slta_memperilah_konseling_kesehatan_remaja',
                'label' => 'Jumlah SLTP, SLTA memperoleh konseling kesehatan remaja',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3607 Child
                'id' => 3668,
                'name' => 'ks_jumlah_taman_kanak_kanak_melaksanakan_kesehatan_anak_pra_sekolah',
                'label' => 'Jumlah Taman Kanak-Kanak (TK) melaksanakan kesehatan Anak Pra Sekolah',
                'is_parent' => false,
                'indicator_parent_id' => 3607,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3608 Child
                'id' => 3669,
                'name' => 'kor_jumlah_kelompok_olahraga_yang_dibina',
                'label' => 'Jumlah kelompok/klub olah raga yang dibina',
                'is_parent' => false,
                'indicator_parent_id' => 3608,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3608 Child
                'id' => 3670,
                'name' => 'kor_jumlah_yang_mendapatkan_pelayanan_kesehatan_olahraga',
                'label' => 'Jumlah yang mendapatkan pelayanan kesehatan olah raga',
                'is_parent' => false,
                'indicator_parent_id' => 3608,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3609 Child
                'id' => 3670,
                'name' => 'kpkm_frekuensi_penyuluhan_dalam_wilayah_puskesmas_untuk_kel_potensial',
                'label' => 'Frekuensi Penyuluhan dalam wilayah puskesmas untuk kel. potensial',
                'is_parent' => false,
                'indicator_parent_id' => 3609,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3609 Child
                'id' => 3671,
                'name' => 'kpkm_frekuensi_penyuluhan_kelompok_dalam_wilayah',
                'label' => 'Frekuensi Penyuluhan Kelompok dalam Wilayah',
                'is_parent' => false,
                'indicator_parent_id' => 3609,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3609 Child
                'id' => 3672,
                'name' => 'kpkm_jumlah_desa_yang_melaksanakan_phbs',
                'label' => 'Jumlah desa yang melaksanakan PHBS',
                'is_parent' => false,
                'indicator_parent_id' => 3609,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3609 Child
                'id' => 3673,
                'name' => 'kpkm_jumlah_penduduk_yang_merokok',
                'label' => 'Jumlah penduduk yang merokok',
                'is_parent' => false,
                'indicator_parent_id' => 3609,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3674,
                'name' => 'ukbm_jumlah_posyandu',
                'label' => 'Jumlah Posyandu',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3675,
                'name' => 'ukbm_jumlah_posyandu_pratama',
                'label' => 'Jumlah Posyandu Pratama',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3676,
                'name' => 'ukbm_jumlah_posyandu_madya',
                'label' => 'Jumlah Posyandu Madya',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3677,
                'name' => 'ukbm_jumlah_posyandu_purnama',
                'label' => 'Jumlah Posyandu Purnama',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3677,
                'name' => 'ukbm_jumlah_kader_posyandu',
                'label' => 'Jumlah Kader Posyandu',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3678,
                'name' => 'ukbm_jumlah_kader_posyandu_yang_aktif',
                'label' => 'Jumlah Kader Posyandu yang aktif',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3679,
                'name' => 'ukbm_jumlah_tanaman_obat_keluarga',
                'label' => 'Jumlah Tanaman obat keluarga (TOGA)',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3680,
                'name' => 'ukbm_jumlah_toga_pratama',
                'label' => 'Jumlah TOGA Pratama',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3681,
                'name' => 'ukbm_jumlah_toga_madya',
                'label' => 'Jumlah TOGA Madya',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3682,
                'name' => 'ukbm_jumlah_toga_purnama',
                'label' => 'Jumlah TOGA Purnama',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3683,
                'name' => 'ukbm_jumlah_toga_mandiri',
                'label' => 'Jumlah TOGA Mandiri',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3684,
                'name' => 'ukbm_jumlah_posyandu_lansia',
                'label' => 'Jumlah Posyandu / Kelompok Lansia',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3685,
                'name' => 'ukbm_jumlah_kelompok_remaja',
                'label' => 'Jumlah Kelompok Remaja',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3610 Child
                'id' => 3686,
                'name' => 'ukbm_jumlah_desa_yang_melaksanakan_phbs_strata_iii_dan_iv',
                'label' => 'Jumlah Desa yang melaksanakan PHBS Strata III dan IV',
                'is_parent' => false,
                'indicator_parent_id' => 3610,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [ // 3611 Child
                'id' => 3687,
                'name' => '',
                'label' => '',
                'is_parent' => false,
                'indicator_parent_id' => 3611,
                'unit_label' => 'orang',
                'created_at' => date("Y-m-d H:i:s"),
                'updated_at' => date("Y-m-d H:i:s"),
            ],
            [
                "id" => 3687,
                "name" => 'kl_jumlah_rumah_seluruhnya',
                "label" => 'Jumlah Rumah seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3688,
                "name" => 'kl_jumlah_rumah_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Rumah yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3689,
                "name" => 'kl_jumlah_rumah_yang_memenuhi_syarat_sanitasi_dasar',
                "label" => 'Jumlah Rumah yang memenuhi syarat sanitasi dasar',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3690,
                "name" => 'kl_jumlah_jamban_keluarga_seluruhnya',
                "label" => 'Jumlah Jamban Keluarga Seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3691,
                "name" => 'kl_jumlah_jamban_keluarga_yang_diperiksa',
                "label" => 'Jumlah Jamban keluarga yang diperiksa',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3692,
                "name" => 'kl_jumlah_jamban_keluarga_yang_memenuhi_syarat_kesehatan',
                "label" => 'Jumlah Jamban Keluarga yang memenuhi syarat kesehatan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3693,
                "name" => 'kl_jumlah_tempat_sampah_seluruhnya',
                "label" => 'Jumlah Tempat Sampah Seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3694,
                "name" => 'kl_jumlah_tempat_sampah_yang_diperiksa',
                "label" => 'Jumlah Tempat Sampah yang diperiksa',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3695,
                "name" => 'kl_jumlah_tempat_sampah_yang_memenuhi_syarat_kesehatan',
                "label" => 'Jumlah Tempat Sampah yang memenuhi syarat kesehatan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3696,
                "name" => 'kl_jumlah_rumah_dengan_pengelolaan_air_limbah_seluruhnya',
                "label" => 'Jumlah Rumah dengan Pengelolaan Air Limbah Seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3697,
                "name" => 'kl_jumlah_rumah_dengan_pengelolaan_air_limbah_yang_diperiksa',
                "label" => 'Jumlah Rumah dengan Pengelolaan Air Limbah yang diperiksa',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3698,
                "name" => 'kl_jumlah_rumah_dengan_pengelolaan_air_limbah_yang_memenuhi_syarat_kesehatan',
                "label" => 'Jumlah Rumah dengan Pengelolaan Air Limbah yang memenuhi syarat kesehatan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3699,
                "name" => 'kl_jumlah_sarana_air_bersih_seluruhnya',
                "label" => 'Jumlah Sarana AIR Bersih seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3700,
                "name" => 'kl_jumlah_sarana_pdam_seluruhnya',
                "label" => 'Jumlah Sarana PDAM seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3701,
                "name" => 'kl_jumlah_sumur_gali_seluruhnya',
                "label" => 'Jumlah Sumur Gali seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3702,
                "name" => 'kl_jumlah_pah_seluruhnya',
                "label" => 'Jumlah PAH seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3703,
                "name" => 'kl_jumlah_spt_seluruhnya',
                "label" => 'Jumlah SPT seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3704,
                "name" => 'kl_jumlah_sarana_air_bersih_yang_diperiksa',
                "label" => 'Jumlah sarana Air Bersih Yang diperiksa',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3705,
                "name" => 'kl_jumlah_sarana_air_bersih_yang_memenuhi_syarat_kesehatan',
                "label" => 'Jumlah sarana Air Bersih Yang memenuhi syarat kesehatan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3706,
                "name" => 'kl_jumlah_sekolah_seluruhnya',
                "label" => 'Jumlah sekolah seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3707,
                "name" => 'kl_jumlah_sekolah_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah sekolah yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3708,
                "name" => 'kl_jumlah_sekolah_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah sekolah yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3709,
                "name" => 'kl_jumlah_madrasah_seluruhnya',
                "label" => 'Jumlah Madrasah seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3710,
                "name" => 'kl_jumlah_madrasah_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Madrasah yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3711,
                "name" => 'kl_jumlah_madrasah_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Madrasah yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3712,
                "name" => 'kl_jumlah_mesjid_seluruhnya',
                "label" => 'Jumlah Mesjid seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3713,
                "name" => 'kl_jumlah_mesjid_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Mesjid yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3714,
                "name" => 'kl_jumlah_mesjid_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Mesjid yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3715,
                "name" => 'kl_jumlah_gereja_seluruhnya',
                "label" => 'Jumlah Gereja seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3716,
                "name" => 'kl_jumlah_gereja_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Gereja yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3717,
                "name" => 'kl_jumlah_gereja_yang_memenuhi_syarat_kesehatan_lingkungan_\'uraian',
                "label" => 'Jumlah Gereja yang memenuhi syarat kesehatan lingkungan \'URAIAN',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3718,
                "name" => 'kl_jumlah_pura_seluruhnya',
                "label" => 'Jumlah Pura seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3719,
                "name" => 'kl_jumlah_pura_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Pura yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3720,
                "name" => 'kl_jumlah_pura_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Pura yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3721,
                "name" => 'kl_jumlah_pesantren_seluruhnya',
                "label" => 'Jumlah Pesantren seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3722,
                "name" => 'kl_jumlah_pesantren_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Pesantren yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3723,
                "name" => 'kl_jumlah_pesantren_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Pesantren yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3724,
                "name" => 'kl_jumlah_majelis_taklim_seluruhnya',
                "label" => 'Jumlah Majelis Taklim seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3725,
                "name" => 'kl_jumlah_majelis_taklim_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Majelis Taklim yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3726,
                "name" => 'kl_jumlah_majelis_taklim_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Majelis Taklim yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3727,
                "name" => 'kl_jumlah_kantor_seluruhnya',
                "label" => 'Jumlah Kantor seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3728,
                "name" => 'kl_jumlah_kantor_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Kantor yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3729,
                "name" => 'kl_jumlah_kantor_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Kantor yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3730,
                "name" => 'kl_jumlah_hotel_seluruhnya',
                "label" => 'Jumlah Hotel seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3731,
                "name" => 'kl_jumlah_hotel_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Hotel yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3732,
                "name" => 'kl_jumlah_hotel_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Hotel yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3733,
                "name" => 'kl_jumlah_toko_seluruhnya',
                "label" => 'Jumlah Toko seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3734,
                "name" => 'kl_jumlah_toko_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Toko yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3735,
                "name" => 'kl_jumlah_toko_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Toko yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3736,
                "name" => 'kl_jumlah_pasar_seluruhnya',
                "label" => 'Jumlah Pasar seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3737,
                "name" => 'kl_jumlah_pasar_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Pasar yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3738,
                "name" => 'kl_jumlah_pasar_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Pasar yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3739,
                "name" => 'kl_jumlah_restoran_/_r._makan_seluruhnya',
                "label" => 'Jumlah Restoran / R. Makan seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3740,
                "name" => 'kl_jumlah_restoran_/_r._makan_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Restoran / R. Makan yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3741,
                "name" => 'kl_jumlah_restoran_/_r._makan_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Restoran / R. Makan yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3742,
                "name" => 'kl_jumlah_salon_kecantikan_seluruhnya',
                "label" => 'Jumlah Salon Kecantikan seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3743,
                "name" => 'kl_jumlah_salon_kecantikan_yang_diperiksa_kesehatan_lingkungannya',
                "label" => 'Jumlah Salon Kecantikan yang diperiksa kesehatan lingkungannya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3744,
                "name" => 'kl_jumlah_salon_kecantikan_yang_memenuhi_syarat_kesehatan_lingkungan',
                "label" => 'Jumlah Salon Kecantikan yang memenuhi syarat kesehatan lingkungan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3745,
                "name" => 'kl_jumlah_industri_rumah_tangga_makanan_dan_minuman_seluruhnya',
                "label" => 'Jumlah industri rumah tangga makanan dan minuman seluruhnya',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3746,
                "name" => 'kl_jumlah_industri_rumah_tangga_makanan_dan_minuman_yang_diperiksa_kesehatan_',
                "label" => 'Jumlah industri rumah tangga makanan dan minuman yang diperiksa kesehatan ',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3747,
                "name" => 'kl_jumlah_industri_rumah_tangga_yang_memenuhi_syarat_kesehatan',
                "label" => 'Jumlah industri rumah tangga yang memenuhi syarat kesehatan',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3748,
                "name" => 'kl_jumlah_tempat_pengelolaan_pestisida_(_tp2_)',
                "label" => 'Jumlah Tempat Pengelolaan Pestisida ( TP2 )',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3749,
                "name" => 'kl_jumlah_tp2_yang_diperiksa',
                "label" => 'Jumlah TP2 yang diperiksa',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ], [
                "id" => 3750,
                "name" => 'kl_jumlah_tp2_yang_memenuhi_syarat',
                "label" => 'Jumlah TP2 yang memenuhi syarat',
                "is_parent" => false,
                "indicator_parent_id" => 3611,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3751,
                "name" => 'lab_jumlah_spesimen_darah_yang_diperiksa',
                "label" => 'Jumlah spesimen darah yang diperiksa',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3752,
                "name" => 'lab_jumlah_spesimen_air_seni_yang_diperiksa',
                "label" => 'Jumlah spesimen air seni yang diperiksa',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3753,
                "name" => 'lab_jumlah_spesimen_tinja_yang_diperiksa',
                "label" => 'Jumlah spesimen tinja yang diperiksa',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3754,
                "name" => 'lab_jumlah_pemeriksaan_bta/tbc_(sputum)',
                "label" => 'Jumlah pemeriksaan BTA/TBC (sputum)',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3755,
                "name" => 'lab_jumlah_pemeriksaan_bta/tbc_(sputum)_positif',
                "label" => 'Jumlah pemeriksaan BTA/TBC (sputum) positif',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3756,
                "name" => 'lab_jumlah_pemeriksaan_darah_untuk_malaria',
                "label" => 'Jumlah pemeriksaan darah untuk Malaria',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3757,
                "name" => 'lab_jumlah_pemeriksaan_darah_untuk_malaria_positif',
                "label" => 'Jumlah pemeriksaan darah untuk Malaria positif',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3758,
                "name" =>
                'lab_jumlah_pemeriksaan_darah_untuk_malaria_positif_p._falsiparum',
                "label" =>
                'Jumlah pemeriksaan darah untuk Malaria positif P. Falsiparum',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3759,
                "name" => 'lab_jumlah_pemeriksaan_bta/kusta_(reitz_serum)',
                "label" => 'Jumlah pemeriksaan BTA/Kusta (Reitz serum)',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3760,
                "name" => 'lab_jumlah_pemeriksaan_bta/kusta_(reitz_serum)_positif',
                "label" => 'Jumlah pemeriksaan BTA/Kusta (Reitz serum) positif',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3761,
                "name" => 'lab_jumlah_pemeriksaan_laboratorium_lainnya',
                "label" => 'Jumlah pemeriksaan Laboratorium lainnya',
                "is_parent" => false,
                "indicator_parent_id" => 3612,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [ // 3613 Child
                "id" => 3762,
                "name" => 'jm_frekuensi_pertemuan_jaminan_mutu',
                "label" => 'Frekuensi pertemuan jaminan mutu',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3763,
                "name" => 'jm_jumlah_identifikasi_masalah_jaminan_mutu',
                "label" => 'Jumlah identifikasi masalah jaminan mutu',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3764,
                "name" => 'jm_jumlah_audit_kasus_dalam_rangka_peningkatan_mutu_',
                "label" => 'Jumlah audit kasus dalam rangka peningkatan mutu ',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3765,
                "name" => 'jm_jumlah_seluruh_sop_yang_telah_dibuat_sebelumnya',
                "label" => 'Jumlah seluruh SOP yang telah dibuat sebelumnya',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3766,
                "name" => 'jm_jumlah_sop_yang_telah_dibuat_bulan_ini',
                "label" => 'Jumlah SOP yang telah dibuat bulan ini',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3767,
                "name" => 'jm_jumlah_sop_yang_telah_dikembangkan',
                "label" => 'Jumlah SOP yang telah dikembangkan',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3768,
                "name" => 'jm_jumlah_seluruh_daftar_tilik_yang_telah_dibuat_sebelumnya',
                "label" => 'Jumlah seluruh daftar tilik yang telah dibuat sebelumnya',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3769,
                "name" => 'jm_jumlah_daftar_tilik_yang_telah_dibuat_bulan_ini',
                "label" => 'Jumlah daftar tilik yang telah dibuat bulan ini',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3770,
                "name" => 'jm_jumlah_survey_kepatuhan/tilik_kepatuhan_terhadap_sop',
                "label" => 'Jumlah survey kepatuhan/tilik kepatuhan terhadap SOP',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ],
            [
                "id" => 3771,
                "name" => 'jm_jumlah_survey_kepuasan_pelanggan_bulan_ini',
                "label" => 'Jumlah survey kepuasan pelanggan bulan ini',
                "is_parent" => false,
                "indicator_parent_id" => 3613,
                "unit_label" => 'orang',
                "created_at" => date("Y-m-d H:i:s"),
                "updated_at" => date("Y-m-d H:i:s")
            ]
        ];
    }
}
